// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: poam/v1/poam.proto

package poamv1

import (
	v1 "github.com/mchorfa/xoscal/proto/oscal/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlanOfActionAndMilestones represents a plan of action and milestones item
type PlanOfActionAndMilestones struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Metadata         *v1.Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ImportSsp        *ImportSsp             `protobuf:"bytes,3,opt,name=import_ssp,json=importSsp,proto3" json:"import_ssp,omitempty"`
	LocalDefinitions *LocalDefinitions      `protobuf:"bytes,4,opt,name=local_definitions,json=localDefinitions,proto3" json:"local_definitions,omitempty"`
	Risks            []*Risk                `protobuf:"bytes,5,rep,name=risks,proto3" json:"risks,omitempty"`
	BackMatter       *v1.BackMatter         `protobuf:"bytes,6,opt,name=back_matter,json=backMatter,proto3" json:"back_matter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlanOfActionAndMilestones) Reset() {
	*x = PlanOfActionAndMilestones{}
	mi := &file_poam_v1_poam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanOfActionAndMilestones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanOfActionAndMilestones) ProtoMessage() {}

func (x *PlanOfActionAndMilestones) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanOfActionAndMilestones.ProtoReflect.Descriptor instead.
func (*PlanOfActionAndMilestones) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{0}
}

func (x *PlanOfActionAndMilestones) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *PlanOfActionAndMilestones) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PlanOfActionAndMilestones) GetImportSsp() *ImportSsp {
	if x != nil {
		return x.ImportSsp
	}
	return nil
}

func (x *PlanOfActionAndMilestones) GetLocalDefinitions() *LocalDefinitions {
	if x != nil {
		return x.LocalDefinitions
	}
	return nil
}

func (x *PlanOfActionAndMilestones) GetRisks() []*Risk {
	if x != nil {
		return x.Risks
	}
	return nil
}

func (x *PlanOfActionAndMilestones) GetBackMatter() *v1.BackMatter {
	if x != nil {
		return x.BackMatter
	}
	return nil
}

// ImportSsp represents an imported system security plan
type ImportSsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          *v1.URIReference       `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSsp) Reset() {
	*x = ImportSsp{}
	mi := &file_poam_v1_poam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSsp) ProtoMessage() {}

func (x *ImportSsp) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSsp.ProtoReflect.Descriptor instead.
func (*ImportSsp) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{1}
}

func (x *ImportSsp) GetHref() *v1.URIReference {
	if x != nil {
		return x.Href
	}
	return nil
}

func (x *ImportSsp) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// LocalDefinitions represents local definitions for POAM
type LocalDefinitions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Components     []*Component           `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	InventoryItems []*InventoryItem       `protobuf:"bytes,2,rep,name=inventory_items,json=inventoryItems,proto3" json:"inventory_items,omitempty"`
	Users          []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalDefinitions) Reset() {
	*x = LocalDefinitions{}
	mi := &file_poam_v1_poam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDefinitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDefinitions) ProtoMessage() {}

func (x *LocalDefinitions) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDefinitions.ProtoReflect.Descriptor instead.
func (*LocalDefinitions) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{2}
}

func (x *LocalDefinitions) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *LocalDefinitions) GetInventoryItems() []*InventoryItem {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

func (x *LocalDefinitions) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Component represents a system component
type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,7,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_poam_v1_poam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{3}
}

func (x *Component) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Component) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Component) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Component) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Component) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Component) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Component) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// InventoryItem represents an inventory item
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Description   *v1.MarkupLine         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_poam_v1_poam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryItem) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *InventoryItem) GetDescription() *v1.MarkupLine {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *InventoryItem) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *InventoryItem) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *InventoryItem) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// User represents a system user
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ShortName     string                 `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,7,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_poam_v1_poam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *User) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *User) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *User) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *User) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Risk represents a risk
type Risk struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Uuid                *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title               *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description         *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Statement           *v1.MarkupMultiline    `protobuf:"bytes,4,opt,name=statement,proto3" json:"statement,omitempty"`
	Status              *RiskStatus            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	MitigatingFactors   []*MitigatingFactor    `protobuf:"bytes,6,rep,name=mitigating_factors,json=mitigatingFactors,proto3" json:"mitigating_factors,omitempty"`
	Deadline            *v1.DateTime           `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Remediations        []*Response            `protobuf:"bytes,8,rep,name=remediations,proto3" json:"remediations,omitempty"`
	RiskLog             *RiskLog               `protobuf:"bytes,9,opt,name=risk_log,json=riskLog,proto3" json:"risk_log,omitempty"`
	RelatedObservations []*RelatedObservation  `protobuf:"bytes,10,rep,name=related_observations,json=relatedObservations,proto3" json:"related_observations,omitempty"`
	Props               []*v1.Property         `protobuf:"bytes,11,rep,name=props,proto3" json:"props,omitempty"`
	Links               []*v1.Link             `protobuf:"bytes,12,rep,name=links,proto3" json:"links,omitempty"`
	Remarks             []*v1.MarkupMultiline  `protobuf:"bytes,13,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Risk) Reset() {
	*x = Risk{}
	mi := &file_poam_v1_poam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Risk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Risk) ProtoMessage() {}

func (x *Risk) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Risk.ProtoReflect.Descriptor instead.
func (*Risk) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{6}
}

func (x *Risk) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Risk) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Risk) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Risk) GetStatement() *v1.MarkupMultiline {
	if x != nil {
		return x.Statement
	}
	return nil
}

func (x *Risk) GetStatus() *RiskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Risk) GetMitigatingFactors() []*MitigatingFactor {
	if x != nil {
		return x.MitigatingFactors
	}
	return nil
}

func (x *Risk) GetDeadline() *v1.DateTime {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Risk) GetRemediations() []*Response {
	if x != nil {
		return x.Remediations
	}
	return nil
}

func (x *Risk) GetRiskLog() *RiskLog {
	if x != nil {
		return x.RiskLog
	}
	return nil
}

func (x *Risk) GetRelatedObservations() []*RelatedObservation {
	if x != nil {
		return x.RelatedObservations
	}
	return nil
}

func (x *Risk) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Risk) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Risk) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// RiskStatus represents risk status
type RiskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskStatus) Reset() {
	*x = RiskStatus{}
	mi := &file_poam_v1_poam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskStatus) ProtoMessage() {}

func (x *RiskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskStatus.ProtoReflect.Descriptor instead.
func (*RiskStatus) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{7}
}

func (x *RiskStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RiskStatus) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// MitigatingFactor represents a mitigating factor
type MitigatingFactor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ImplementationUuid *v1.UUID               `protobuf:"bytes,2,opt,name=implementation_uuid,json=implementationUuid,proto3" json:"implementation_uuid,omitempty"`
	Description        *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Props              []*v1.Property         `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty"`
	Links              []*v1.Link             `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	Subjects           []*SubjectReference    `protobuf:"bytes,6,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MitigatingFactor) Reset() {
	*x = MitigatingFactor{}
	mi := &file_poam_v1_poam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitigatingFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitigatingFactor) ProtoMessage() {}

func (x *MitigatingFactor) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitigatingFactor.ProtoReflect.Descriptor instead.
func (*MitigatingFactor) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{8}
}

func (x *MitigatingFactor) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *MitigatingFactor) GetImplementationUuid() *v1.UUID {
	if x != nil {
		return x.ImplementationUuid
	}
	return nil
}

func (x *MitigatingFactor) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *MitigatingFactor) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *MitigatingFactor) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MitigatingFactor) GetSubjects() []*SubjectReference {
	if x != nil {
		return x.Subjects
	}
	return nil
}

// SubjectReference represents a subject reference
type SubjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectUuid   *v1.UUID               `protobuf:"bytes,1,opt,name=subject_uuid,json=subjectUuid,proto3" json:"subject_uuid,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectReference) Reset() {
	*x = SubjectReference{}
	mi := &file_poam_v1_poam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectReference) ProtoMessage() {}

func (x *SubjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectReference.ProtoReflect.Descriptor instead.
func (*SubjectReference) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{9}
}

func (x *SubjectReference) GetSubjectUuid() *v1.UUID {
	if x != nil {
		return x.SubjectUuid
	}
	return nil
}

func (x *SubjectReference) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SubjectReference) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *SubjectReference) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *SubjectReference) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Response represents a risk response/remediation
type Response struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title            *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Deadline         *v1.DateTime           `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Status           *ResponseStatus        `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ResponsibleRoles []*ResponsibleRole     `protobuf:"bytes,6,rep,name=responsible_roles,json=responsibleRoles,proto3" json:"responsible_roles,omitempty"`
	RelatedTasks     []*RelatedTask         `protobuf:"bytes,7,rep,name=related_tasks,json=relatedTasks,proto3" json:"related_tasks,omitempty"`
	Subjects         []*SubjectReference    `protobuf:"bytes,8,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Props            []*v1.Property         `protobuf:"bytes,9,rep,name=props,proto3" json:"props,omitempty"`
	Links            []*v1.Link             `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Remarks          []*v1.MarkupMultiline  `protobuf:"bytes,11,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_poam_v1_poam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Response) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Response) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Response) GetDeadline() *v1.DateTime {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Response) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Response) GetResponsibleRoles() []*ResponsibleRole {
	if x != nil {
		return x.ResponsibleRoles
	}
	return nil
}

func (x *Response) GetRelatedTasks() []*RelatedTask {
	if x != nil {
		return x.RelatedTasks
	}
	return nil
}

func (x *Response) GetSubjects() []*SubjectReference {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Response) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Response) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Response) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// ResponseStatus represents response status
type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_poam_v1_poam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ResponseStatus) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// ResponsibleRole represents a responsible role
type ResponsibleRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        *v1.Token              `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PartyUuids    []*v1.UUID             `protobuf:"bytes,2,rep,name=party_uuids,json=partyUuids,proto3" json:"party_uuids,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,4,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsibleRole) Reset() {
	*x = ResponsibleRole{}
	mi := &file_poam_v1_poam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsibleRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsibleRole) ProtoMessage() {}

func (x *ResponsibleRole) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsibleRole.ProtoReflect.Descriptor instead.
func (*ResponsibleRole) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{12}
}

func (x *ResponsibleRole) GetRoleId() *v1.Token {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *ResponsibleRole) GetPartyUuids() []*v1.UUID {
	if x != nil {
		return x.PartyUuids
	}
	return nil
}

func (x *ResponsibleRole) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *ResponsibleRole) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// RelatedTask represents a related task
type RelatedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUuid      *v1.UUID               `protobuf:"bytes,1,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedTask) Reset() {
	*x = RelatedTask{}
	mi := &file_poam_v1_poam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedTask) ProtoMessage() {}

func (x *RelatedTask) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedTask.ProtoReflect.Descriptor instead.
func (*RelatedTask) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{13}
}

func (x *RelatedTask) GetTaskUuid() *v1.UUID {
	if x != nil {
		return x.TaskUuid
	}
	return nil
}

func (x *RelatedTask) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *RelatedTask) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *RelatedTask) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RelatedTask) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// RiskLog represents a risk log
type RiskLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RiskLogEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskLog) Reset() {
	*x = RiskLog{}
	mi := &file_poam_v1_poam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskLog) ProtoMessage() {}

func (x *RiskLog) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskLog.ProtoReflect.Descriptor instead.
func (*RiskLog) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{14}
}

func (x *RiskLog) GetEntries() []*RiskLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RiskLogEntry represents a risk log entry
type RiskLogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title            *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Start            *v1.DateTime           `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End              *v1.DateTime           `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	Props            []*v1.Property         `protobuf:"bytes,6,rep,name=props,proto3" json:"props,omitempty"`
	Links            []*v1.Link             `protobuf:"bytes,7,rep,name=links,proto3" json:"links,omitempty"`
	LoggedBy         []*LoggedBy            `protobuf:"bytes,8,rep,name=logged_by,json=loggedBy,proto3" json:"logged_by,omitempty"`
	StatusChange     *RiskStatus            `protobuf:"bytes,9,opt,name=status_change,json=statusChange,proto3" json:"status_change,omitempty"`
	RelatedResponses []*RelatedResponse     `protobuf:"bytes,10,rep,name=related_responses,json=relatedResponses,proto3" json:"related_responses,omitempty"`
	Remarks          []*v1.MarkupMultiline  `protobuf:"bytes,11,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RiskLogEntry) Reset() {
	*x = RiskLogEntry{}
	mi := &file_poam_v1_poam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskLogEntry) ProtoMessage() {}

func (x *RiskLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskLogEntry.ProtoReflect.Descriptor instead.
func (*RiskLogEntry) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{15}
}

func (x *RiskLogEntry) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *RiskLogEntry) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *RiskLogEntry) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *RiskLogEntry) GetStart() *v1.DateTime {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RiskLogEntry) GetEnd() *v1.DateTime {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RiskLogEntry) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *RiskLogEntry) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RiskLogEntry) GetLoggedBy() []*LoggedBy {
	if x != nil {
		return x.LoggedBy
	}
	return nil
}

func (x *RiskLogEntry) GetStatusChange() *RiskStatus {
	if x != nil {
		return x.StatusChange
	}
	return nil
}

func (x *RiskLogEntry) GetRelatedResponses() []*RelatedResponse {
	if x != nil {
		return x.RelatedResponses
	}
	return nil
}

func (x *RiskLogEntry) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// LoggedBy represents who logged the entry
type LoggedBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyUuid     *v1.UUID               `protobuf:"bytes,1,opt,name=party_uuid,json=partyUuid,proto3" json:"party_uuid,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggedBy) Reset() {
	*x = LoggedBy{}
	mi := &file_poam_v1_poam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggedBy) ProtoMessage() {}

func (x *LoggedBy) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggedBy.ProtoReflect.Descriptor instead.
func (*LoggedBy) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{16}
}

func (x *LoggedBy) GetPartyUuid() *v1.UUID {
	if x != nil {
		return x.PartyUuid
	}
	return nil
}

func (x *LoggedBy) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *LoggedBy) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *LoggedBy) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *LoggedBy) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// RelatedResponse represents a related risk response
type RelatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseUuid  *v1.UUID               `protobuf:"bytes,1,opt,name=response_uuid,json=responseUuid,proto3" json:"response_uuid,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,2,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	RelatedTasks  []*RelatedTask         `protobuf:"bytes,4,rep,name=related_tasks,json=relatedTasks,proto3" json:"related_tasks,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedResponse) Reset() {
	*x = RelatedResponse{}
	mi := &file_poam_v1_poam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedResponse) ProtoMessage() {}

func (x *RelatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedResponse.ProtoReflect.Descriptor instead.
func (*RelatedResponse) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{17}
}

func (x *RelatedResponse) GetResponseUuid() *v1.UUID {
	if x != nil {
		return x.ResponseUuid
	}
	return nil
}

func (x *RelatedResponse) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *RelatedResponse) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RelatedResponse) GetRelatedTasks() []*RelatedTask {
	if x != nil {
		return x.RelatedTasks
	}
	return nil
}

func (x *RelatedResponse) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// RelatedObservation represents a related observation
type RelatedObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObservationUuid *v1.UUID               `protobuf:"bytes,1,opt,name=observation_uuid,json=observationUuid,proto3" json:"observation_uuid,omitempty"`
	Remarks         []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelatedObservation) Reset() {
	*x = RelatedObservation{}
	mi := &file_poam_v1_poam_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedObservation) ProtoMessage() {}

func (x *RelatedObservation) ProtoReflect() protoreflect.Message {
	mi := &file_poam_v1_poam_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedObservation.ProtoReflect.Descriptor instead.
func (*RelatedObservation) Descriptor() ([]byte, []int) {
	return file_poam_v1_poam_proto_rawDescGZIP(), []int{18}
}

func (x *RelatedObservation) GetObservationUuid() *v1.UUID {
	if x != nil {
		return x.ObservationUuid
	}
	return nil
}

func (x *RelatedObservation) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

var File_poam_v1_poam_proto protoreflect.FileDescriptor

const file_poam_v1_poam_proto_rawDesc = "" +
	"\n" +
	"\x12poam/v1/poam.proto\x12\roscal.poam.v1\x1a\x16common/v1/common.proto\"\xed\x02\n" +
	"\x19PlanOfActionAndMilestones\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.oscal.common.v1.MetadataR\bmetadata\x127\n" +
	"\n" +
	"import_ssp\x18\x03 \x01(\v2\x18.oscal.poam.v1.ImportSspR\timportSsp\x12L\n" +
	"\x11local_definitions\x18\x04 \x01(\v2\x1f.oscal.poam.v1.LocalDefinitionsR\x10localDefinitions\x12)\n" +
	"\x05risks\x18\x05 \x03(\v2\x13.oscal.poam.v1.RiskR\x05risks\x12<\n" +
	"\vback_matter\x18\x06 \x01(\v2\x1b.oscal.common.v1.BackMatterR\n" +
	"backMatter\"z\n" +
	"\tImportSsp\x121\n" +
	"\x04href\x18\x01 \x01(\v2\x1d.oscal.common.v1.URIReferenceR\x04href\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xbe\x01\n" +
	"\x10LocalDefinitions\x128\n" +
	"\n" +
	"components\x18\x01 \x03(\v2\x18.oscal.poam.v1.ComponentR\n" +
	"components\x12E\n" +
	"\x0finventory_items\x18\x02 \x03(\v2\x1c.oscal.poam.v1.InventoryItemR\x0einventoryItems\x12)\n" +
	"\x05users\x18\x03 \x03(\v2\x13.oscal.poam.v1.UserR\x05users\"\x9c\x02\n" +
	"\tComponent\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\x05props\x18\x05 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x06 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\a \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x93\x02\n" +
	"\rInventoryItem\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12=\n" +
	"\vdescription\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\vdescription\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xc4\x02\n" +
	"\x04User\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"short_name\x18\x03 \x01(\tR\tshortName\x12B\n" +
	"\vdescription\x18\x04 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x05 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x06 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\a \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x82\x06\n" +
	"\x04Risk\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12>\n" +
	"\tstatement\x18\x04 \x01(\v2 .oscal.common.v1.MarkupMultilineR\tstatement\x121\n" +
	"\x06status\x18\x05 \x01(\v2\x19.oscal.poam.v1.RiskStatusR\x06status\x12N\n" +
	"\x12mitigating_factors\x18\x06 \x03(\v2\x1f.oscal.poam.v1.MitigatingFactorR\x11mitigatingFactors\x125\n" +
	"\bdeadline\x18\a \x01(\v2\x19.oscal.common.v1.DateTimeR\bdeadline\x12;\n" +
	"\fremediations\x18\b \x03(\v2\x17.oscal.poam.v1.ResponseR\fremediations\x121\n" +
	"\brisk_log\x18\t \x01(\v2\x16.oscal.poam.v1.RiskLogR\ariskLog\x12T\n" +
	"\x14related_observations\x18\n" +
	" \x03(\v2!.oscal.poam.v1.RelatedObservationR\x13relatedObservations\x12/\n" +
	"\x05props\x18\v \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\f \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\r \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"^\n" +
	"\n" +
	"RiskStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xe4\x02\n" +
	"\x10MitigatingFactor\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12F\n" +
	"\x13implementation_uuid\x18\x02 \x01(\v2\x15.oscal.common.v1.UUIDR\x12implementationUuid\x12B\n" +
	"\vdescription\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x04 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x05 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12;\n" +
	"\bsubjects\x18\x06 \x03(\v2\x1f.oscal.poam.v1.SubjectReferenceR\bsubjects\"\x99\x02\n" +
	"\x10SubjectReference\x128\n" +
	"\fsubject_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\vsubjectUuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xff\x04\n" +
	"\bResponse\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x125\n" +
	"\bdeadline\x18\x04 \x01(\v2\x19.oscal.common.v1.DateTimeR\bdeadline\x125\n" +
	"\x06status\x18\x05 \x01(\v2\x1d.oscal.poam.v1.ResponseStatusR\x06status\x12K\n" +
	"\x11responsible_roles\x18\x06 \x03(\v2\x1e.oscal.poam.v1.ResponsibleRoleR\x10responsibleRoles\x12?\n" +
	"\rrelated_tasks\x18\a \x03(\v2\x1a.oscal.poam.v1.RelatedTaskR\frelatedTasks\x12;\n" +
	"\bsubjects\x18\b \x03(\v2\x1f.oscal.poam.v1.SubjectReferenceR\bsubjects\x12/\n" +
	"\x05props\x18\t \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\v \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"b\n" +
	"\x0eResponseStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xe7\x01\n" +
	"\x0fResponsibleRole\x12/\n" +
	"\arole_id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\x06roleId\x126\n" +
	"\vparty_uuids\x18\x02 \x03(\v2\x15.oscal.common.v1.UUIDR\n" +
	"partyUuids\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12:\n" +
	"\aremarks\x18\x04 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x8e\x02\n" +
	"\vRelatedTask\x122\n" +
	"\ttask_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\btaskUuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"@\n" +
	"\aRiskLog\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.oscal.poam.v1.RiskLogEntryR\aentries\"\xeb\x04\n" +
	"\fRiskLogEntry\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05start\x18\x04 \x01(\v2\x19.oscal.common.v1.DateTimeR\x05start\x12+\n" +
	"\x03end\x18\x05 \x01(\v2\x19.oscal.common.v1.DateTimeR\x03end\x12/\n" +
	"\x05props\x18\x06 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\a \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x124\n" +
	"\tlogged_by\x18\b \x03(\v2\x17.oscal.poam.v1.LoggedByR\bloggedBy\x12>\n" +
	"\rstatus_change\x18\t \x01(\v2\x19.oscal.poam.v1.RiskStatusR\fstatusChange\x12K\n" +
	"\x11related_responses\x18\n" +
	" \x03(\v2\x1e.oscal.poam.v1.RelatedResponseR\x10relatedResponses\x12:\n" +
	"\aremarks\x18\v \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x8d\x02\n" +
	"\bLoggedBy\x124\n" +
	"\n" +
	"party_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\tpartyUuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xa8\x02\n" +
	"\x0fRelatedResponse\x12:\n" +
	"\rresponse_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\fresponseUuid\x12/\n" +
	"\x05props\x18\x02 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x03 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12?\n" +
	"\rrelated_tasks\x18\x04 \x03(\v2\x1a.oscal.poam.v1.RelatedTaskR\frelatedTasks\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x92\x01\n" +
	"\x12RelatedObservation\x12@\n" +
	"\x10observation_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x0fobservationUuid\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarksB6Z4github.com/mchorfa/xoscal/proto/oscal/poam/v1;poamv1b\x06proto3"

var (
	file_poam_v1_poam_proto_rawDescOnce sync.Once
	file_poam_v1_poam_proto_rawDescData []byte
)

func file_poam_v1_poam_proto_rawDescGZIP() []byte {
	file_poam_v1_poam_proto_rawDescOnce.Do(func() {
		file_poam_v1_poam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poam_v1_poam_proto_rawDesc), len(file_poam_v1_poam_proto_rawDesc)))
	})
	return file_poam_v1_poam_proto_rawDescData
}

var file_poam_v1_poam_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_poam_v1_poam_proto_goTypes = []any{
	(*PlanOfActionAndMilestones)(nil), // 0: oscal.poam.v1.PlanOfActionAndMilestones
	(*ImportSsp)(nil),                 // 1: oscal.poam.v1.ImportSsp
	(*LocalDefinitions)(nil),          // 2: oscal.poam.v1.LocalDefinitions
	(*Component)(nil),                 // 3: oscal.poam.v1.Component
	(*InventoryItem)(nil),             // 4: oscal.poam.v1.InventoryItem
	(*User)(nil),                      // 5: oscal.poam.v1.User
	(*Risk)(nil),                      // 6: oscal.poam.v1.Risk
	(*RiskStatus)(nil),                // 7: oscal.poam.v1.RiskStatus
	(*MitigatingFactor)(nil),          // 8: oscal.poam.v1.MitigatingFactor
	(*SubjectReference)(nil),          // 9: oscal.poam.v1.SubjectReference
	(*Response)(nil),                  // 10: oscal.poam.v1.Response
	(*ResponseStatus)(nil),            // 11: oscal.poam.v1.ResponseStatus
	(*ResponsibleRole)(nil),           // 12: oscal.poam.v1.ResponsibleRole
	(*RelatedTask)(nil),               // 13: oscal.poam.v1.RelatedTask
	(*RiskLog)(nil),                   // 14: oscal.poam.v1.RiskLog
	(*RiskLogEntry)(nil),              // 15: oscal.poam.v1.RiskLogEntry
	(*LoggedBy)(nil),                  // 16: oscal.poam.v1.LoggedBy
	(*RelatedResponse)(nil),           // 17: oscal.poam.v1.RelatedResponse
	(*RelatedObservation)(nil),        // 18: oscal.poam.v1.RelatedObservation
	(*v1.UUID)(nil),                   // 19: oscal.common.v1.UUID
	(*v1.Metadata)(nil),               // 20: oscal.common.v1.Metadata
	(*v1.BackMatter)(nil),             // 21: oscal.common.v1.BackMatter
	(*v1.URIReference)(nil),           // 22: oscal.common.v1.URIReference
	(*v1.MarkupMultiline)(nil),        // 23: oscal.common.v1.MarkupMultiline
	(*v1.Property)(nil),               // 24: oscal.common.v1.Property
	(*v1.Link)(nil),                   // 25: oscal.common.v1.Link
	(*v1.MarkupLine)(nil),             // 26: oscal.common.v1.MarkupLine
	(*v1.DateTime)(nil),               // 27: oscal.common.v1.DateTime
	(*v1.Token)(nil),                  // 28: oscal.common.v1.Token
}
var file_poam_v1_poam_proto_depIdxs = []int32{
	19, // 0: oscal.poam.v1.PlanOfActionAndMilestones.uuid:type_name -> oscal.common.v1.UUID
	20, // 1: oscal.poam.v1.PlanOfActionAndMilestones.metadata:type_name -> oscal.common.v1.Metadata
	1,  // 2: oscal.poam.v1.PlanOfActionAndMilestones.import_ssp:type_name -> oscal.poam.v1.ImportSsp
	2,  // 3: oscal.poam.v1.PlanOfActionAndMilestones.local_definitions:type_name -> oscal.poam.v1.LocalDefinitions
	6,  // 4: oscal.poam.v1.PlanOfActionAndMilestones.risks:type_name -> oscal.poam.v1.Risk
	21, // 5: oscal.poam.v1.PlanOfActionAndMilestones.back_matter:type_name -> oscal.common.v1.BackMatter
	22, // 6: oscal.poam.v1.ImportSsp.href:type_name -> oscal.common.v1.URIReference
	23, // 7: oscal.poam.v1.ImportSsp.remarks:type_name -> oscal.common.v1.MarkupMultiline
	3,  // 8: oscal.poam.v1.LocalDefinitions.components:type_name -> oscal.poam.v1.Component
	4,  // 9: oscal.poam.v1.LocalDefinitions.inventory_items:type_name -> oscal.poam.v1.InventoryItem
	5,  // 10: oscal.poam.v1.LocalDefinitions.users:type_name -> oscal.poam.v1.User
	19, // 11: oscal.poam.v1.Component.uuid:type_name -> oscal.common.v1.UUID
	24, // 12: oscal.poam.v1.Component.props:type_name -> oscal.common.v1.Property
	25, // 13: oscal.poam.v1.Component.links:type_name -> oscal.common.v1.Link
	23, // 14: oscal.poam.v1.Component.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 15: oscal.poam.v1.InventoryItem.uuid:type_name -> oscal.common.v1.UUID
	26, // 16: oscal.poam.v1.InventoryItem.description:type_name -> oscal.common.v1.MarkupLine
	24, // 17: oscal.poam.v1.InventoryItem.props:type_name -> oscal.common.v1.Property
	25, // 18: oscal.poam.v1.InventoryItem.links:type_name -> oscal.common.v1.Link
	23, // 19: oscal.poam.v1.InventoryItem.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 20: oscal.poam.v1.User.uuid:type_name -> oscal.common.v1.UUID
	23, // 21: oscal.poam.v1.User.description:type_name -> oscal.common.v1.MarkupMultiline
	24, // 22: oscal.poam.v1.User.props:type_name -> oscal.common.v1.Property
	25, // 23: oscal.poam.v1.User.links:type_name -> oscal.common.v1.Link
	23, // 24: oscal.poam.v1.User.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 25: oscal.poam.v1.Risk.uuid:type_name -> oscal.common.v1.UUID
	26, // 26: oscal.poam.v1.Risk.title:type_name -> oscal.common.v1.MarkupLine
	23, // 27: oscal.poam.v1.Risk.description:type_name -> oscal.common.v1.MarkupMultiline
	23, // 28: oscal.poam.v1.Risk.statement:type_name -> oscal.common.v1.MarkupMultiline
	7,  // 29: oscal.poam.v1.Risk.status:type_name -> oscal.poam.v1.RiskStatus
	8,  // 30: oscal.poam.v1.Risk.mitigating_factors:type_name -> oscal.poam.v1.MitigatingFactor
	27, // 31: oscal.poam.v1.Risk.deadline:type_name -> oscal.common.v1.DateTime
	10, // 32: oscal.poam.v1.Risk.remediations:type_name -> oscal.poam.v1.Response
	14, // 33: oscal.poam.v1.Risk.risk_log:type_name -> oscal.poam.v1.RiskLog
	18, // 34: oscal.poam.v1.Risk.related_observations:type_name -> oscal.poam.v1.RelatedObservation
	24, // 35: oscal.poam.v1.Risk.props:type_name -> oscal.common.v1.Property
	25, // 36: oscal.poam.v1.Risk.links:type_name -> oscal.common.v1.Link
	23, // 37: oscal.poam.v1.Risk.remarks:type_name -> oscal.common.v1.MarkupMultiline
	23, // 38: oscal.poam.v1.RiskStatus.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 39: oscal.poam.v1.MitigatingFactor.uuid:type_name -> oscal.common.v1.UUID
	19, // 40: oscal.poam.v1.MitigatingFactor.implementation_uuid:type_name -> oscal.common.v1.UUID
	23, // 41: oscal.poam.v1.MitigatingFactor.description:type_name -> oscal.common.v1.MarkupMultiline
	24, // 42: oscal.poam.v1.MitigatingFactor.props:type_name -> oscal.common.v1.Property
	25, // 43: oscal.poam.v1.MitigatingFactor.links:type_name -> oscal.common.v1.Link
	9,  // 44: oscal.poam.v1.MitigatingFactor.subjects:type_name -> oscal.poam.v1.SubjectReference
	19, // 45: oscal.poam.v1.SubjectReference.subject_uuid:type_name -> oscal.common.v1.UUID
	26, // 46: oscal.poam.v1.SubjectReference.title:type_name -> oscal.common.v1.MarkupLine
	24, // 47: oscal.poam.v1.SubjectReference.props:type_name -> oscal.common.v1.Property
	25, // 48: oscal.poam.v1.SubjectReference.links:type_name -> oscal.common.v1.Link
	23, // 49: oscal.poam.v1.SubjectReference.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 50: oscal.poam.v1.Response.uuid:type_name -> oscal.common.v1.UUID
	26, // 51: oscal.poam.v1.Response.title:type_name -> oscal.common.v1.MarkupLine
	23, // 52: oscal.poam.v1.Response.description:type_name -> oscal.common.v1.MarkupMultiline
	27, // 53: oscal.poam.v1.Response.deadline:type_name -> oscal.common.v1.DateTime
	11, // 54: oscal.poam.v1.Response.status:type_name -> oscal.poam.v1.ResponseStatus
	12, // 55: oscal.poam.v1.Response.responsible_roles:type_name -> oscal.poam.v1.ResponsibleRole
	13, // 56: oscal.poam.v1.Response.related_tasks:type_name -> oscal.poam.v1.RelatedTask
	9,  // 57: oscal.poam.v1.Response.subjects:type_name -> oscal.poam.v1.SubjectReference
	24, // 58: oscal.poam.v1.Response.props:type_name -> oscal.common.v1.Property
	25, // 59: oscal.poam.v1.Response.links:type_name -> oscal.common.v1.Link
	23, // 60: oscal.poam.v1.Response.remarks:type_name -> oscal.common.v1.MarkupMultiline
	23, // 61: oscal.poam.v1.ResponseStatus.remarks:type_name -> oscal.common.v1.MarkupMultiline
	28, // 62: oscal.poam.v1.ResponsibleRole.role_id:type_name -> oscal.common.v1.Token
	19, // 63: oscal.poam.v1.ResponsibleRole.party_uuids:type_name -> oscal.common.v1.UUID
	24, // 64: oscal.poam.v1.ResponsibleRole.props:type_name -> oscal.common.v1.Property
	23, // 65: oscal.poam.v1.ResponsibleRole.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 66: oscal.poam.v1.RelatedTask.task_uuid:type_name -> oscal.common.v1.UUID
	26, // 67: oscal.poam.v1.RelatedTask.title:type_name -> oscal.common.v1.MarkupLine
	24, // 68: oscal.poam.v1.RelatedTask.props:type_name -> oscal.common.v1.Property
	25, // 69: oscal.poam.v1.RelatedTask.links:type_name -> oscal.common.v1.Link
	23, // 70: oscal.poam.v1.RelatedTask.remarks:type_name -> oscal.common.v1.MarkupMultiline
	15, // 71: oscal.poam.v1.RiskLog.entries:type_name -> oscal.poam.v1.RiskLogEntry
	19, // 72: oscal.poam.v1.RiskLogEntry.uuid:type_name -> oscal.common.v1.UUID
	26, // 73: oscal.poam.v1.RiskLogEntry.title:type_name -> oscal.common.v1.MarkupLine
	23, // 74: oscal.poam.v1.RiskLogEntry.description:type_name -> oscal.common.v1.MarkupMultiline
	27, // 75: oscal.poam.v1.RiskLogEntry.start:type_name -> oscal.common.v1.DateTime
	27, // 76: oscal.poam.v1.RiskLogEntry.end:type_name -> oscal.common.v1.DateTime
	24, // 77: oscal.poam.v1.RiskLogEntry.props:type_name -> oscal.common.v1.Property
	25, // 78: oscal.poam.v1.RiskLogEntry.links:type_name -> oscal.common.v1.Link
	16, // 79: oscal.poam.v1.RiskLogEntry.logged_by:type_name -> oscal.poam.v1.LoggedBy
	7,  // 80: oscal.poam.v1.RiskLogEntry.status_change:type_name -> oscal.poam.v1.RiskStatus
	17, // 81: oscal.poam.v1.RiskLogEntry.related_responses:type_name -> oscal.poam.v1.RelatedResponse
	23, // 82: oscal.poam.v1.RiskLogEntry.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 83: oscal.poam.v1.LoggedBy.party_uuid:type_name -> oscal.common.v1.UUID
	26, // 84: oscal.poam.v1.LoggedBy.title:type_name -> oscal.common.v1.MarkupLine
	24, // 85: oscal.poam.v1.LoggedBy.props:type_name -> oscal.common.v1.Property
	25, // 86: oscal.poam.v1.LoggedBy.links:type_name -> oscal.common.v1.Link
	23, // 87: oscal.poam.v1.LoggedBy.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 88: oscal.poam.v1.RelatedResponse.response_uuid:type_name -> oscal.common.v1.UUID
	24, // 89: oscal.poam.v1.RelatedResponse.props:type_name -> oscal.common.v1.Property
	25, // 90: oscal.poam.v1.RelatedResponse.links:type_name -> oscal.common.v1.Link
	13, // 91: oscal.poam.v1.RelatedResponse.related_tasks:type_name -> oscal.poam.v1.RelatedTask
	23, // 92: oscal.poam.v1.RelatedResponse.remarks:type_name -> oscal.common.v1.MarkupMultiline
	19, // 93: oscal.poam.v1.RelatedObservation.observation_uuid:type_name -> oscal.common.v1.UUID
	23, // 94: oscal.poam.v1.RelatedObservation.remarks:type_name -> oscal.common.v1.MarkupMultiline
	95, // [95:95] is the sub-list for method output_type
	95, // [95:95] is the sub-list for method input_type
	95, // [95:95] is the sub-list for extension type_name
	95, // [95:95] is the sub-list for extension extendee
	0,  // [0:95] is the sub-list for field type_name
}

func init() { file_poam_v1_poam_proto_init() }
func file_poam_v1_poam_proto_init() {
	if File_poam_v1_poam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poam_v1_poam_proto_rawDesc), len(file_poam_v1_poam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poam_v1_poam_proto_goTypes,
		DependencyIndexes: file_poam_v1_poam_proto_depIdxs,
		MessageInfos:      file_poam_v1_poam_proto_msgTypes,
	}.Build()
	File_poam_v1_poam_proto = out.File
	file_poam_v1_poam_proto_goTypes = nil
	file_poam_v1_poam_proto_depIdxs = nil
}
