// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: services/v1/oscal_service.proto

package servicesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OscalService_GetCatalog_FullMethodName                = "/oscal.services.v1.OscalService/GetCatalog"
	OscalService_ListCatalogs_FullMethodName              = "/oscal.services.v1.OscalService/ListCatalogs"
	OscalService_CreateCatalog_FullMethodName             = "/oscal.services.v1.OscalService/CreateCatalog"
	OscalService_UpdateCatalog_FullMethodName             = "/oscal.services.v1.OscalService/UpdateCatalog"
	OscalService_DeleteCatalog_FullMethodName             = "/oscal.services.v1.OscalService/DeleteCatalog"
	OscalService_GetProfile_FullMethodName                = "/oscal.services.v1.OscalService/GetProfile"
	OscalService_ListProfiles_FullMethodName              = "/oscal.services.v1.OscalService/ListProfiles"
	OscalService_CreateProfile_FullMethodName             = "/oscal.services.v1.OscalService/CreateProfile"
	OscalService_UpdateProfile_FullMethodName             = "/oscal.services.v1.OscalService/UpdateProfile"
	OscalService_DeleteProfile_FullMethodName             = "/oscal.services.v1.OscalService/DeleteProfile"
	OscalService_GetComponentDefinition_FullMethodName    = "/oscal.services.v1.OscalService/GetComponentDefinition"
	OscalService_ListComponentDefinitions_FullMethodName  = "/oscal.services.v1.OscalService/ListComponentDefinitions"
	OscalService_CreateComponentDefinition_FullMethodName = "/oscal.services.v1.OscalService/CreateComponentDefinition"
	OscalService_UpdateComponentDefinition_FullMethodName = "/oscal.services.v1.OscalService/UpdateComponentDefinition"
	OscalService_DeleteComponentDefinition_FullMethodName = "/oscal.services.v1.OscalService/DeleteComponentDefinition"
	OscalService_GetSsp_FullMethodName                    = "/oscal.services.v1.OscalService/GetSsp"
	OscalService_ListSsps_FullMethodName                  = "/oscal.services.v1.OscalService/ListSsps"
	OscalService_CreateSsp_FullMethodName                 = "/oscal.services.v1.OscalService/CreateSsp"
	OscalService_UpdateSsp_FullMethodName                 = "/oscal.services.v1.OscalService/UpdateSsp"
	OscalService_DeleteSsp_FullMethodName                 = "/oscal.services.v1.OscalService/DeleteSsp"
	OscalService_GetAssessmentPlan_FullMethodName         = "/oscal.services.v1.OscalService/GetAssessmentPlan"
	OscalService_ListAssessmentPlans_FullMethodName       = "/oscal.services.v1.OscalService/ListAssessmentPlans"
	OscalService_CreateAssessmentPlan_FullMethodName      = "/oscal.services.v1.OscalService/CreateAssessmentPlan"
	OscalService_UpdateAssessmentPlan_FullMethodName      = "/oscal.services.v1.OscalService/UpdateAssessmentPlan"
	OscalService_DeleteAssessmentPlan_FullMethodName      = "/oscal.services.v1.OscalService/DeleteAssessmentPlan"
	OscalService_GetAssessmentResults_FullMethodName      = "/oscal.services.v1.OscalService/GetAssessmentResults"
	OscalService_ListAssessmentResults_FullMethodName     = "/oscal.services.v1.OscalService/ListAssessmentResults"
	OscalService_CreateAssessmentResults_FullMethodName   = "/oscal.services.v1.OscalService/CreateAssessmentResults"
	OscalService_UpdateAssessmentResults_FullMethodName   = "/oscal.services.v1.OscalService/UpdateAssessmentResults"
	OscalService_DeleteAssessmentResults_FullMethodName   = "/oscal.services.v1.OscalService/DeleteAssessmentResults"
	OscalService_GetPoam_FullMethodName                   = "/oscal.services.v1.OscalService/GetPoam"
	OscalService_ListPoams_FullMethodName                 = "/oscal.services.v1.OscalService/ListPoams"
	OscalService_CreatePoam_FullMethodName                = "/oscal.services.v1.OscalService/CreatePoam"
	OscalService_UpdatePoam_FullMethodName                = "/oscal.services.v1.OscalService/UpdatePoam"
	OscalService_DeletePoam_FullMethodName                = "/oscal.services.v1.OscalService/DeletePoam"
	OscalService_GetMapping_FullMethodName                = "/oscal.services.v1.OscalService/GetMapping"
	OscalService_ListMappings_FullMethodName              = "/oscal.services.v1.OscalService/ListMappings"
	OscalService_CreateMapping_FullMethodName             = "/oscal.services.v1.OscalService/CreateMapping"
	OscalService_UpdateMapping_FullMethodName             = "/oscal.services.v1.OscalService/UpdateMapping"
	OscalService_DeleteMapping_FullMethodName             = "/oscal.services.v1.OscalService/DeleteMapping"
	OscalService_Search_FullMethodName                    = "/oscal.services.v1.OscalService/Search"
)

// OscalServiceClient is the client API for OscalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OSCAL Service provides CRUD operations for all OSCAL models
type OscalServiceClient interface {
	// Catalog operations
	GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error)
	ListCatalogs(ctx context.Context, in *ListCatalogsRequest, opts ...grpc.CallOption) (*ListCatalogsResponse, error)
	CreateCatalog(ctx context.Context, in *CreateCatalogRequest, opts ...grpc.CallOption) (*CreateCatalogResponse, error)
	UpdateCatalog(ctx context.Context, in *UpdateCatalogRequest, opts ...grpc.CallOption) (*UpdateCatalogResponse, error)
	DeleteCatalog(ctx context.Context, in *DeleteCatalogRequest, opts ...grpc.CallOption) (*DeleteCatalogResponse, error)
	// Profile operations
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	// Component Definition operations
	GetComponentDefinition(ctx context.Context, in *GetComponentDefinitionRequest, opts ...grpc.CallOption) (*GetComponentDefinitionResponse, error)
	ListComponentDefinitions(ctx context.Context, in *ListComponentDefinitionsRequest, opts ...grpc.CallOption) (*ListComponentDefinitionsResponse, error)
	CreateComponentDefinition(ctx context.Context, in *CreateComponentDefinitionRequest, opts ...grpc.CallOption) (*CreateComponentDefinitionResponse, error)
	UpdateComponentDefinition(ctx context.Context, in *UpdateComponentDefinitionRequest, opts ...grpc.CallOption) (*UpdateComponentDefinitionResponse, error)
	DeleteComponentDefinition(ctx context.Context, in *DeleteComponentDefinitionRequest, opts ...grpc.CallOption) (*DeleteComponentDefinitionResponse, error)
	// SSP operations
	GetSsp(ctx context.Context, in *GetSspRequest, opts ...grpc.CallOption) (*GetSspResponse, error)
	ListSsps(ctx context.Context, in *ListSspsRequest, opts ...grpc.CallOption) (*ListSspsResponse, error)
	CreateSsp(ctx context.Context, in *CreateSspRequest, opts ...grpc.CallOption) (*CreateSspResponse, error)
	UpdateSsp(ctx context.Context, in *UpdateSspRequest, opts ...grpc.CallOption) (*UpdateSspResponse, error)
	DeleteSsp(ctx context.Context, in *DeleteSspRequest, opts ...grpc.CallOption) (*DeleteSspResponse, error)
	// Assessment Plan operations
	GetAssessmentPlan(ctx context.Context, in *GetAssessmentPlanRequest, opts ...grpc.CallOption) (*GetAssessmentPlanResponse, error)
	ListAssessmentPlans(ctx context.Context, in *ListAssessmentPlansRequest, opts ...grpc.CallOption) (*ListAssessmentPlansResponse, error)
	CreateAssessmentPlan(ctx context.Context, in *CreateAssessmentPlanRequest, opts ...grpc.CallOption) (*CreateAssessmentPlanResponse, error)
	UpdateAssessmentPlan(ctx context.Context, in *UpdateAssessmentPlanRequest, opts ...grpc.CallOption) (*UpdateAssessmentPlanResponse, error)
	DeleteAssessmentPlan(ctx context.Context, in *DeleteAssessmentPlanRequest, opts ...grpc.CallOption) (*DeleteAssessmentPlanResponse, error)
	// Assessment Results operations
	GetAssessmentResults(ctx context.Context, in *GetAssessmentResultsRequest, opts ...grpc.CallOption) (*GetAssessmentResultsResponse, error)
	ListAssessmentResults(ctx context.Context, in *ListAssessmentResultsRequest, opts ...grpc.CallOption) (*ListAssessmentResultsResponse, error)
	CreateAssessmentResults(ctx context.Context, in *CreateAssessmentResultsRequest, opts ...grpc.CallOption) (*CreateAssessmentResultsResponse, error)
	UpdateAssessmentResults(ctx context.Context, in *UpdateAssessmentResultsRequest, opts ...grpc.CallOption) (*UpdateAssessmentResultsResponse, error)
	DeleteAssessmentResults(ctx context.Context, in *DeleteAssessmentResultsRequest, opts ...grpc.CallOption) (*DeleteAssessmentResultsResponse, error)
	// POA&M operations
	GetPoam(ctx context.Context, in *GetPoamRequest, opts ...grpc.CallOption) (*GetPoamResponse, error)
	ListPoams(ctx context.Context, in *ListPoamsRequest, opts ...grpc.CallOption) (*ListPoamsResponse, error)
	CreatePoam(ctx context.Context, in *CreatePoamRequest, opts ...grpc.CallOption) (*CreatePoamResponse, error)
	UpdatePoam(ctx context.Context, in *UpdatePoamRequest, opts ...grpc.CallOption) (*UpdatePoamResponse, error)
	DeletePoam(ctx context.Context, in *DeletePoamRequest, opts ...grpc.CallOption) (*DeletePoamResponse, error)
	// Mapping operations
	GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error)
	ListMappings(ctx context.Context, in *ListMappingsRequest, opts ...grpc.CallOption) (*ListMappingsResponse, error)
	CreateMapping(ctx context.Context, in *CreateMappingRequest, opts ...grpc.CallOption) (*CreateMappingResponse, error)
	UpdateMapping(ctx context.Context, in *UpdateMappingRequest, opts ...grpc.CallOption) (*UpdateMappingResponse, error)
	DeleteMapping(ctx context.Context, in *DeleteMappingRequest, opts ...grpc.CallOption) (*DeleteMappingResponse, error)
	// Search operations
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type oscalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOscalServiceClient(cc grpc.ClientConnInterface) OscalServiceClient {
	return &oscalServiceClient{cc}
}

func (c *oscalServiceClient) GetCatalog(ctx context.Context, in *GetCatalogRequest, opts ...grpc.CallOption) (*GetCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogResponse)
	err := c.cc.Invoke(ctx, OscalService_GetCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListCatalogs(ctx context.Context, in *ListCatalogsRequest, opts ...grpc.CallOption) (*ListCatalogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatalogsResponse)
	err := c.cc.Invoke(ctx, OscalService_ListCatalogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateCatalog(ctx context.Context, in *CreateCatalogRequest, opts ...grpc.CallOption) (*CreateCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCatalogResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateCatalog(ctx context.Context, in *UpdateCatalogRequest, opts ...grpc.CallOption) (*UpdateCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCatalogResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteCatalog(ctx context.Context, in *DeleteCatalogRequest, opts ...grpc.CallOption) (*DeleteCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCatalogResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, OscalService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, OscalService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetComponentDefinition(ctx context.Context, in *GetComponentDefinitionRequest, opts ...grpc.CallOption) (*GetComponentDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComponentDefinitionResponse)
	err := c.cc.Invoke(ctx, OscalService_GetComponentDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListComponentDefinitions(ctx context.Context, in *ListComponentDefinitionsRequest, opts ...grpc.CallOption) (*ListComponentDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListComponentDefinitionsResponse)
	err := c.cc.Invoke(ctx, OscalService_ListComponentDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateComponentDefinition(ctx context.Context, in *CreateComponentDefinitionRequest, opts ...grpc.CallOption) (*CreateComponentDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateComponentDefinitionResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateComponentDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateComponentDefinition(ctx context.Context, in *UpdateComponentDefinitionRequest, opts ...grpc.CallOption) (*UpdateComponentDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateComponentDefinitionResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateComponentDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteComponentDefinition(ctx context.Context, in *DeleteComponentDefinitionRequest, opts ...grpc.CallOption) (*DeleteComponentDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteComponentDefinitionResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteComponentDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetSsp(ctx context.Context, in *GetSspRequest, opts ...grpc.CallOption) (*GetSspResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSspResponse)
	err := c.cc.Invoke(ctx, OscalService_GetSsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListSsps(ctx context.Context, in *ListSspsRequest, opts ...grpc.CallOption) (*ListSspsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSspsResponse)
	err := c.cc.Invoke(ctx, OscalService_ListSsps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateSsp(ctx context.Context, in *CreateSspRequest, opts ...grpc.CallOption) (*CreateSspResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSspResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateSsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateSsp(ctx context.Context, in *UpdateSspRequest, opts ...grpc.CallOption) (*UpdateSspResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSspResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateSsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteSsp(ctx context.Context, in *DeleteSspRequest, opts ...grpc.CallOption) (*DeleteSspResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSspResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteSsp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetAssessmentPlan(ctx context.Context, in *GetAssessmentPlanRequest, opts ...grpc.CallOption) (*GetAssessmentPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssessmentPlanResponse)
	err := c.cc.Invoke(ctx, OscalService_GetAssessmentPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListAssessmentPlans(ctx context.Context, in *ListAssessmentPlansRequest, opts ...grpc.CallOption) (*ListAssessmentPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssessmentPlansResponse)
	err := c.cc.Invoke(ctx, OscalService_ListAssessmentPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateAssessmentPlan(ctx context.Context, in *CreateAssessmentPlanRequest, opts ...grpc.CallOption) (*CreateAssessmentPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssessmentPlanResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateAssessmentPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateAssessmentPlan(ctx context.Context, in *UpdateAssessmentPlanRequest, opts ...grpc.CallOption) (*UpdateAssessmentPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssessmentPlanResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateAssessmentPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteAssessmentPlan(ctx context.Context, in *DeleteAssessmentPlanRequest, opts ...grpc.CallOption) (*DeleteAssessmentPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssessmentPlanResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteAssessmentPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetAssessmentResults(ctx context.Context, in *GetAssessmentResultsRequest, opts ...grpc.CallOption) (*GetAssessmentResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssessmentResultsResponse)
	err := c.cc.Invoke(ctx, OscalService_GetAssessmentResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListAssessmentResults(ctx context.Context, in *ListAssessmentResultsRequest, opts ...grpc.CallOption) (*ListAssessmentResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssessmentResultsResponse)
	err := c.cc.Invoke(ctx, OscalService_ListAssessmentResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateAssessmentResults(ctx context.Context, in *CreateAssessmentResultsRequest, opts ...grpc.CallOption) (*CreateAssessmentResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssessmentResultsResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateAssessmentResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateAssessmentResults(ctx context.Context, in *UpdateAssessmentResultsRequest, opts ...grpc.CallOption) (*UpdateAssessmentResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssessmentResultsResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateAssessmentResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteAssessmentResults(ctx context.Context, in *DeleteAssessmentResultsRequest, opts ...grpc.CallOption) (*DeleteAssessmentResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssessmentResultsResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteAssessmentResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetPoam(ctx context.Context, in *GetPoamRequest, opts ...grpc.CallOption) (*GetPoamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoamResponse)
	err := c.cc.Invoke(ctx, OscalService_GetPoam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListPoams(ctx context.Context, in *ListPoamsRequest, opts ...grpc.CallOption) (*ListPoamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoamsResponse)
	err := c.cc.Invoke(ctx, OscalService_ListPoams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreatePoam(ctx context.Context, in *CreatePoamRequest, opts ...grpc.CallOption) (*CreatePoamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePoamResponse)
	err := c.cc.Invoke(ctx, OscalService_CreatePoam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdatePoam(ctx context.Context, in *UpdatePoamRequest, opts ...grpc.CallOption) (*UpdatePoamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePoamResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdatePoam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeletePoam(ctx context.Context, in *DeletePoamRequest, opts ...grpc.CallOption) (*DeletePoamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePoamResponse)
	err := c.cc.Invoke(ctx, OscalService_DeletePoam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) GetMapping(ctx context.Context, in *GetMappingRequest, opts ...grpc.CallOption) (*GetMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMappingResponse)
	err := c.cc.Invoke(ctx, OscalService_GetMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) ListMappings(ctx context.Context, in *ListMappingsRequest, opts ...grpc.CallOption) (*ListMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMappingsResponse)
	err := c.cc.Invoke(ctx, OscalService_ListMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) CreateMapping(ctx context.Context, in *CreateMappingRequest, opts ...grpc.CallOption) (*CreateMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMappingResponse)
	err := c.cc.Invoke(ctx, OscalService_CreateMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) UpdateMapping(ctx context.Context, in *UpdateMappingRequest, opts ...grpc.CallOption) (*UpdateMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMappingResponse)
	err := c.cc.Invoke(ctx, OscalService_UpdateMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) DeleteMapping(ctx context.Context, in *DeleteMappingRequest, opts ...grpc.CallOption) (*DeleteMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMappingResponse)
	err := c.cc.Invoke(ctx, OscalService_DeleteMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oscalServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, OscalService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OscalServiceServer is the server API for OscalService service.
// All implementations must embed UnimplementedOscalServiceServer
// for forward compatibility.
//
// OSCAL Service provides CRUD operations for all OSCAL models
type OscalServiceServer interface {
	// Catalog operations
	GetCatalog(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error)
	ListCatalogs(context.Context, *ListCatalogsRequest) (*ListCatalogsResponse, error)
	CreateCatalog(context.Context, *CreateCatalogRequest) (*CreateCatalogResponse, error)
	UpdateCatalog(context.Context, *UpdateCatalogRequest) (*UpdateCatalogResponse, error)
	DeleteCatalog(context.Context, *DeleteCatalogRequest) (*DeleteCatalogResponse, error)
	// Profile operations
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	// Component Definition operations
	GetComponentDefinition(context.Context, *GetComponentDefinitionRequest) (*GetComponentDefinitionResponse, error)
	ListComponentDefinitions(context.Context, *ListComponentDefinitionsRequest) (*ListComponentDefinitionsResponse, error)
	CreateComponentDefinition(context.Context, *CreateComponentDefinitionRequest) (*CreateComponentDefinitionResponse, error)
	UpdateComponentDefinition(context.Context, *UpdateComponentDefinitionRequest) (*UpdateComponentDefinitionResponse, error)
	DeleteComponentDefinition(context.Context, *DeleteComponentDefinitionRequest) (*DeleteComponentDefinitionResponse, error)
	// SSP operations
	GetSsp(context.Context, *GetSspRequest) (*GetSspResponse, error)
	ListSsps(context.Context, *ListSspsRequest) (*ListSspsResponse, error)
	CreateSsp(context.Context, *CreateSspRequest) (*CreateSspResponse, error)
	UpdateSsp(context.Context, *UpdateSspRequest) (*UpdateSspResponse, error)
	DeleteSsp(context.Context, *DeleteSspRequest) (*DeleteSspResponse, error)
	// Assessment Plan operations
	GetAssessmentPlan(context.Context, *GetAssessmentPlanRequest) (*GetAssessmentPlanResponse, error)
	ListAssessmentPlans(context.Context, *ListAssessmentPlansRequest) (*ListAssessmentPlansResponse, error)
	CreateAssessmentPlan(context.Context, *CreateAssessmentPlanRequest) (*CreateAssessmentPlanResponse, error)
	UpdateAssessmentPlan(context.Context, *UpdateAssessmentPlanRequest) (*UpdateAssessmentPlanResponse, error)
	DeleteAssessmentPlan(context.Context, *DeleteAssessmentPlanRequest) (*DeleteAssessmentPlanResponse, error)
	// Assessment Results operations
	GetAssessmentResults(context.Context, *GetAssessmentResultsRequest) (*GetAssessmentResultsResponse, error)
	ListAssessmentResults(context.Context, *ListAssessmentResultsRequest) (*ListAssessmentResultsResponse, error)
	CreateAssessmentResults(context.Context, *CreateAssessmentResultsRequest) (*CreateAssessmentResultsResponse, error)
	UpdateAssessmentResults(context.Context, *UpdateAssessmentResultsRequest) (*UpdateAssessmentResultsResponse, error)
	DeleteAssessmentResults(context.Context, *DeleteAssessmentResultsRequest) (*DeleteAssessmentResultsResponse, error)
	// POA&M operations
	GetPoam(context.Context, *GetPoamRequest) (*GetPoamResponse, error)
	ListPoams(context.Context, *ListPoamsRequest) (*ListPoamsResponse, error)
	CreatePoam(context.Context, *CreatePoamRequest) (*CreatePoamResponse, error)
	UpdatePoam(context.Context, *UpdatePoamRequest) (*UpdatePoamResponse, error)
	DeletePoam(context.Context, *DeletePoamRequest) (*DeletePoamResponse, error)
	// Mapping operations
	GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error)
	ListMappings(context.Context, *ListMappingsRequest) (*ListMappingsResponse, error)
	CreateMapping(context.Context, *CreateMappingRequest) (*CreateMappingResponse, error)
	UpdateMapping(context.Context, *UpdateMappingRequest) (*UpdateMappingResponse, error)
	DeleteMapping(context.Context, *DeleteMappingRequest) (*DeleteMappingResponse, error)
	// Search operations
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedOscalServiceServer()
}

// UnimplementedOscalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOscalServiceServer struct{}

func (UnimplementedOscalServiceServer) GetCatalog(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatalog not implemented")
}
func (UnimplementedOscalServiceServer) ListCatalogs(context.Context, *ListCatalogsRequest) (*ListCatalogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCatalogs not implemented")
}
func (UnimplementedOscalServiceServer) CreateCatalog(context.Context, *CreateCatalogRequest) (*CreateCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCatalog not implemented")
}
func (UnimplementedOscalServiceServer) UpdateCatalog(context.Context, *UpdateCatalogRequest) (*UpdateCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCatalog not implemented")
}
func (UnimplementedOscalServiceServer) DeleteCatalog(context.Context, *DeleteCatalogRequest) (*DeleteCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCatalog not implemented")
}
func (UnimplementedOscalServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedOscalServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedOscalServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedOscalServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedOscalServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedOscalServiceServer) GetComponentDefinition(context.Context, *GetComponentDefinitionRequest) (*GetComponentDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComponentDefinition not implemented")
}
func (UnimplementedOscalServiceServer) ListComponentDefinitions(context.Context, *ListComponentDefinitionsRequest) (*ListComponentDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComponentDefinitions not implemented")
}
func (UnimplementedOscalServiceServer) CreateComponentDefinition(context.Context, *CreateComponentDefinitionRequest) (*CreateComponentDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComponentDefinition not implemented")
}
func (UnimplementedOscalServiceServer) UpdateComponentDefinition(context.Context, *UpdateComponentDefinitionRequest) (*UpdateComponentDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComponentDefinition not implemented")
}
func (UnimplementedOscalServiceServer) DeleteComponentDefinition(context.Context, *DeleteComponentDefinitionRequest) (*DeleteComponentDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComponentDefinition not implemented")
}
func (UnimplementedOscalServiceServer) GetSsp(context.Context, *GetSspRequest) (*GetSspResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSsp not implemented")
}
func (UnimplementedOscalServiceServer) ListSsps(context.Context, *ListSspsRequest) (*ListSspsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSsps not implemented")
}
func (UnimplementedOscalServiceServer) CreateSsp(context.Context, *CreateSspRequest) (*CreateSspResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSsp not implemented")
}
func (UnimplementedOscalServiceServer) UpdateSsp(context.Context, *UpdateSspRequest) (*UpdateSspResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSsp not implemented")
}
func (UnimplementedOscalServiceServer) DeleteSsp(context.Context, *DeleteSspRequest) (*DeleteSspResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSsp not implemented")
}
func (UnimplementedOscalServiceServer) GetAssessmentPlan(context.Context, *GetAssessmentPlanRequest) (*GetAssessmentPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssessmentPlan not implemented")
}
func (UnimplementedOscalServiceServer) ListAssessmentPlans(context.Context, *ListAssessmentPlansRequest) (*ListAssessmentPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssessmentPlans not implemented")
}
func (UnimplementedOscalServiceServer) CreateAssessmentPlan(context.Context, *CreateAssessmentPlanRequest) (*CreateAssessmentPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssessmentPlan not implemented")
}
func (UnimplementedOscalServiceServer) UpdateAssessmentPlan(context.Context, *UpdateAssessmentPlanRequest) (*UpdateAssessmentPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAssessmentPlan not implemented")
}
func (UnimplementedOscalServiceServer) DeleteAssessmentPlan(context.Context, *DeleteAssessmentPlanRequest) (*DeleteAssessmentPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAssessmentPlan not implemented")
}
func (UnimplementedOscalServiceServer) GetAssessmentResults(context.Context, *GetAssessmentResultsRequest) (*GetAssessmentResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssessmentResults not implemented")
}
func (UnimplementedOscalServiceServer) ListAssessmentResults(context.Context, *ListAssessmentResultsRequest) (*ListAssessmentResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssessmentResults not implemented")
}
func (UnimplementedOscalServiceServer) CreateAssessmentResults(context.Context, *CreateAssessmentResultsRequest) (*CreateAssessmentResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssessmentResults not implemented")
}
func (UnimplementedOscalServiceServer) UpdateAssessmentResults(context.Context, *UpdateAssessmentResultsRequest) (*UpdateAssessmentResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAssessmentResults not implemented")
}
func (UnimplementedOscalServiceServer) DeleteAssessmentResults(context.Context, *DeleteAssessmentResultsRequest) (*DeleteAssessmentResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAssessmentResults not implemented")
}
func (UnimplementedOscalServiceServer) GetPoam(context.Context, *GetPoamRequest) (*GetPoamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoam not implemented")
}
func (UnimplementedOscalServiceServer) ListPoams(context.Context, *ListPoamsRequest) (*ListPoamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPoams not implemented")
}
func (UnimplementedOscalServiceServer) CreatePoam(context.Context, *CreatePoamRequest) (*CreatePoamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePoam not implemented")
}
func (UnimplementedOscalServiceServer) UpdatePoam(context.Context, *UpdatePoamRequest) (*UpdatePoamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePoam not implemented")
}
func (UnimplementedOscalServiceServer) DeletePoam(context.Context, *DeletePoamRequest) (*DeletePoamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePoam not implemented")
}
func (UnimplementedOscalServiceServer) GetMapping(context.Context, *GetMappingRequest) (*GetMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMapping not implemented")
}
func (UnimplementedOscalServiceServer) ListMappings(context.Context, *ListMappingsRequest) (*ListMappingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMappings not implemented")
}
func (UnimplementedOscalServiceServer) CreateMapping(context.Context, *CreateMappingRequest) (*CreateMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMapping not implemented")
}
func (UnimplementedOscalServiceServer) UpdateMapping(context.Context, *UpdateMappingRequest) (*UpdateMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMapping not implemented")
}
func (UnimplementedOscalServiceServer) DeleteMapping(context.Context, *DeleteMappingRequest) (*DeleteMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMapping not implemented")
}
func (UnimplementedOscalServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedOscalServiceServer) mustEmbedUnimplementedOscalServiceServer() {}
func (UnimplementedOscalServiceServer) testEmbeddedByValue()                      {}

// UnsafeOscalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OscalServiceServer will
// result in compilation errors.
type UnsafeOscalServiceServer interface {
	mustEmbedUnimplementedOscalServiceServer()
}

func RegisterOscalServiceServer(s grpc.ServiceRegistrar, srv OscalServiceServer) {
	// If the following call panics, it indicates UnimplementedOscalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OscalService_ServiceDesc, srv)
}

func _OscalService_GetCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetCatalog(ctx, req.(*GetCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListCatalogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListCatalogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListCatalogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListCatalogs(ctx, req.(*ListCatalogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateCatalog(ctx, req.(*CreateCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateCatalog(ctx, req.(*UpdateCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteCatalog(ctx, req.(*DeleteCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetComponentDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetComponentDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetComponentDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetComponentDefinition(ctx, req.(*GetComponentDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListComponentDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListComponentDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListComponentDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListComponentDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListComponentDefinitions(ctx, req.(*ListComponentDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateComponentDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateComponentDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateComponentDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateComponentDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateComponentDefinition(ctx, req.(*CreateComponentDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateComponentDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateComponentDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateComponentDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateComponentDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateComponentDefinition(ctx, req.(*UpdateComponentDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteComponentDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteComponentDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteComponentDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteComponentDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteComponentDefinition(ctx, req.(*DeleteComponentDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetSsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetSsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetSsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetSsp(ctx, req.(*GetSspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListSsps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSspsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListSsps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListSsps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListSsps(ctx, req.(*ListSspsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateSsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateSsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateSsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateSsp(ctx, req.(*CreateSspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateSsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateSsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateSsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateSsp(ctx, req.(*UpdateSspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteSsp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSspRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteSsp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteSsp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteSsp(ctx, req.(*DeleteSspRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetAssessmentPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssessmentPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetAssessmentPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetAssessmentPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetAssessmentPlan(ctx, req.(*GetAssessmentPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListAssessmentPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssessmentPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListAssessmentPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListAssessmentPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListAssessmentPlans(ctx, req.(*ListAssessmentPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateAssessmentPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssessmentPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateAssessmentPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateAssessmentPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateAssessmentPlan(ctx, req.(*CreateAssessmentPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateAssessmentPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssessmentPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateAssessmentPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateAssessmentPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateAssessmentPlan(ctx, req.(*UpdateAssessmentPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteAssessmentPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssessmentPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteAssessmentPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteAssessmentPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteAssessmentPlan(ctx, req.(*DeleteAssessmentPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetAssessmentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssessmentResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetAssessmentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetAssessmentResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetAssessmentResults(ctx, req.(*GetAssessmentResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListAssessmentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssessmentResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListAssessmentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListAssessmentResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListAssessmentResults(ctx, req.(*ListAssessmentResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateAssessmentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssessmentResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateAssessmentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateAssessmentResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateAssessmentResults(ctx, req.(*CreateAssessmentResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateAssessmentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssessmentResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateAssessmentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateAssessmentResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateAssessmentResults(ctx, req.(*UpdateAssessmentResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteAssessmentResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssessmentResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteAssessmentResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteAssessmentResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteAssessmentResults(ctx, req.(*DeleteAssessmentResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetPoam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetPoam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetPoam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetPoam(ctx, req.(*GetPoamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListPoams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListPoams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListPoams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListPoams(ctx, req.(*ListPoamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreatePoam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreatePoam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreatePoam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreatePoam(ctx, req.(*CreatePoamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdatePoam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePoamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdatePoam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdatePoam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdatePoam(ctx, req.(*UpdatePoamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeletePoam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeletePoam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeletePoam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeletePoam(ctx, req.(*DeletePoamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_GetMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).GetMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_GetMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).GetMapping(ctx, req.(*GetMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_ListMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).ListMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_ListMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).ListMappings(ctx, req.(*ListMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_CreateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).CreateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_CreateMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).CreateMapping(ctx, req.(*CreateMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_UpdateMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).UpdateMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_UpdateMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).UpdateMapping(ctx, req.(*UpdateMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_DeleteMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).DeleteMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_DeleteMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).DeleteMapping(ctx, req.(*DeleteMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OscalService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OscalServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OscalService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OscalServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OscalService_ServiceDesc is the grpc.ServiceDesc for OscalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OscalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oscal.services.v1.OscalService",
	HandlerType: (*OscalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatalog",
			Handler:    _OscalService_GetCatalog_Handler,
		},
		{
			MethodName: "ListCatalogs",
			Handler:    _OscalService_ListCatalogs_Handler,
		},
		{
			MethodName: "CreateCatalog",
			Handler:    _OscalService_CreateCatalog_Handler,
		},
		{
			MethodName: "UpdateCatalog",
			Handler:    _OscalService_UpdateCatalog_Handler,
		},
		{
			MethodName: "DeleteCatalog",
			Handler:    _OscalService_DeleteCatalog_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _OscalService_GetProfile_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _OscalService_ListProfiles_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _OscalService_CreateProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _OscalService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _OscalService_DeleteProfile_Handler,
		},
		{
			MethodName: "GetComponentDefinition",
			Handler:    _OscalService_GetComponentDefinition_Handler,
		},
		{
			MethodName: "ListComponentDefinitions",
			Handler:    _OscalService_ListComponentDefinitions_Handler,
		},
		{
			MethodName: "CreateComponentDefinition",
			Handler:    _OscalService_CreateComponentDefinition_Handler,
		},
		{
			MethodName: "UpdateComponentDefinition",
			Handler:    _OscalService_UpdateComponentDefinition_Handler,
		},
		{
			MethodName: "DeleteComponentDefinition",
			Handler:    _OscalService_DeleteComponentDefinition_Handler,
		},
		{
			MethodName: "GetSsp",
			Handler:    _OscalService_GetSsp_Handler,
		},
		{
			MethodName: "ListSsps",
			Handler:    _OscalService_ListSsps_Handler,
		},
		{
			MethodName: "CreateSsp",
			Handler:    _OscalService_CreateSsp_Handler,
		},
		{
			MethodName: "UpdateSsp",
			Handler:    _OscalService_UpdateSsp_Handler,
		},
		{
			MethodName: "DeleteSsp",
			Handler:    _OscalService_DeleteSsp_Handler,
		},
		{
			MethodName: "GetAssessmentPlan",
			Handler:    _OscalService_GetAssessmentPlan_Handler,
		},
		{
			MethodName: "ListAssessmentPlans",
			Handler:    _OscalService_ListAssessmentPlans_Handler,
		},
		{
			MethodName: "CreateAssessmentPlan",
			Handler:    _OscalService_CreateAssessmentPlan_Handler,
		},
		{
			MethodName: "UpdateAssessmentPlan",
			Handler:    _OscalService_UpdateAssessmentPlan_Handler,
		},
		{
			MethodName: "DeleteAssessmentPlan",
			Handler:    _OscalService_DeleteAssessmentPlan_Handler,
		},
		{
			MethodName: "GetAssessmentResults",
			Handler:    _OscalService_GetAssessmentResults_Handler,
		},
		{
			MethodName: "ListAssessmentResults",
			Handler:    _OscalService_ListAssessmentResults_Handler,
		},
		{
			MethodName: "CreateAssessmentResults",
			Handler:    _OscalService_CreateAssessmentResults_Handler,
		},
		{
			MethodName: "UpdateAssessmentResults",
			Handler:    _OscalService_UpdateAssessmentResults_Handler,
		},
		{
			MethodName: "DeleteAssessmentResults",
			Handler:    _OscalService_DeleteAssessmentResults_Handler,
		},
		{
			MethodName: "GetPoam",
			Handler:    _OscalService_GetPoam_Handler,
		},
		{
			MethodName: "ListPoams",
			Handler:    _OscalService_ListPoams_Handler,
		},
		{
			MethodName: "CreatePoam",
			Handler:    _OscalService_CreatePoam_Handler,
		},
		{
			MethodName: "UpdatePoam",
			Handler:    _OscalService_UpdatePoam_Handler,
		},
		{
			MethodName: "DeletePoam",
			Handler:    _OscalService_DeletePoam_Handler,
		},
		{
			MethodName: "GetMapping",
			Handler:    _OscalService_GetMapping_Handler,
		},
		{
			MethodName: "ListMappings",
			Handler:    _OscalService_ListMappings_Handler,
		},
		{
			MethodName: "CreateMapping",
			Handler:    _OscalService_CreateMapping_Handler,
		},
		{
			MethodName: "UpdateMapping",
			Handler:    _OscalService_UpdateMapping_Handler,
		},
		{
			MethodName: "DeleteMapping",
			Handler:    _OscalService_DeleteMapping_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _OscalService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/oscal_service.proto",
}
