// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/v1/transparency_graph_service.proto

package servicesv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // artifact | component | service | pipeline_run | model | dataset | identity | document | policy | vulnerability | license | tool
	Urn           string                 `protobuf:"bytes,3,opt,name=urn,proto3" json:"urn,omitempty"`
	LabelsJson    string                 `protobuf:"bytes,4,opt,name=labels_json,json=labelsJson,proto3" json:"labels_json,omitempty"` // JSON blob for key-value labels
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{0}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GraphNode) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

func (x *GraphNode) GetLabelsJson() string {
	if x != nil {
		return x.LabelsJson
	}
	return ""
}

func (x *GraphNode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GraphEdge struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromNode       string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode         string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Relation       string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Qualifier      string                 `protobuf:"bytes,5,opt,name=qualifier,proto3" json:"qualifier,omitempty"`
	ClaimId        string                 `protobuf:"bytes,6,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	EvidenceDigest string                 `protobuf:"bytes,7,opt,name=evidence_digest,json=evidenceDigest,proto3" json:"evidence_digest,omitempty"`
	ProofState     *ProofState            `protobuf:"bytes,8,opt,name=proof_state,json=proofState,proto3" json:"proof_state,omitempty"`
	ValidTime      *TimeWindow            `protobuf:"bytes,9,opt,name=valid_time,json=validTime,proto3" json:"valid_time,omitempty"`
	TrustState     string                 `protobuf:"bytes,10,opt,name=trust_state,json=trustState,proto3" json:"trust_state,omitempty"`
	Weight         float64                `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	ExtensionsJson string                 `protobuf:"bytes,12,opt,name=extensions_json,json=extensionsJson,proto3" json:"extensions_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{1}
}

func (x *GraphEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphEdge) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *GraphEdge) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *GraphEdge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GraphEdge) GetQualifier() string {
	if x != nil {
		return x.Qualifier
	}
	return ""
}

func (x *GraphEdge) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *GraphEdge) GetEvidenceDigest() string {
	if x != nil {
		return x.EvidenceDigest
	}
	return ""
}

func (x *GraphEdge) GetProofState() *ProofState {
	if x != nil {
		return x.ProofState
	}
	return nil
}

func (x *GraphEdge) GetValidTime() *TimeWindow {
	if x != nil {
		return x.ValidTime
	}
	return nil
}

func (x *GraphEdge) GetTrustState() string {
	if x != nil {
		return x.TrustState
	}
	return ""
}

func (x *GraphEdge) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GraphEdge) GetExtensionsJson() string {
	if x != nil {
		return x.ExtensionsJson
	}
	return ""
}

type ProjectEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"` // optional; auto-generated if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEdgeRequest) Reset() {
	*x = ProjectEdgeRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEdgeRequest) ProtoMessage() {}

func (x *ProjectEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEdgeRequest.ProtoReflect.Descriptor instead.
func (*ProjectEdgeRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectEdgeRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *ProjectEdgeRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type ProjectEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *GraphEdge             `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEdgeResponse) Reset() {
	*x = ProjectEdgeResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEdgeResponse) ProtoMessage() {}

func (x *ProjectEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEdgeResponse.ProtoReflect.Descriptor instead.
func (*ProjectEdgeResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectEdgeResponse) GetEdge() *GraphEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

type GetEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeRequest) Reset() {
	*x = GetEdgeRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeRequest) ProtoMessage() {}

func (x *GetEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetEdgeRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type GetEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edge          *GraphEdge             `protobuf:"bytes,1,opt,name=edge,proto3" json:"edge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeResponse) Reset() {
	*x = GetEdgeResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeResponse) ProtoMessage() {}

func (x *GetEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeResponse.ProtoReflect.Descriptor instead.
func (*GetEdgeResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetEdgeResponse) GetEdge() *GraphEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

type ListEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	TrustState    string                 `protobuf:"bytes,4,opt,name=trust_state,json=trustState,proto3" json:"trust_state,omitempty"`
	ValidAfter    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_after,json=validAfter,proto3" json:"valid_after,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEdgesRequest) Reset() {
	*x = ListEdgesRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesRequest) ProtoMessage() {}

func (x *ListEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesRequest.ProtoReflect.Descriptor instead.
func (*ListEdgesRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListEdgesRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *ListEdgesRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *ListEdgesRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListEdgesRequest) GetTrustState() string {
	if x != nil {
		return x.TrustState
	}
	return ""
}

func (x *ListEdgesRequest) GetValidAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAfter
	}
	return nil
}

func (x *ListEdgesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEdgesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*GraphEdge           `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEdgesResponse) Reset() {
	*x = ListEdgesResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesResponse) ProtoMessage() {}

func (x *ListEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesResponse.ProtoReflect.Descriptor instead.
func (*ListEdgesResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListEdgesResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ListEdgesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeRequest) Reset() {
	*x = DeleteEdgeRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeRequest) ProtoMessage() {}

func (x *DeleteEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEdgeRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEdgeRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type DeleteEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeResponse) Reset() {
	*x = DeleteEdgeResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeResponse) ProtoMessage() {}

func (x *DeleteEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEdgeResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEdgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *GraphNode             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeResponse) GetNode() *GraphNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	LabelFilter   string                 `protobuf:"bytes,2,opt,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty"` // JSON path expression e.g. {"framework":"iso-42001"}
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListNodesRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListNodesRequest) GetLabelFilter() string {
	if x != nil {
		return x.LabelFilter
	}
	return ""
}

func (x *ListNodesRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListNodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNodesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListNodesResponse) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type TraverseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartNode     string                 `protobuf:"bytes,1,opt,name=start_node,json=startNode,proto3" json:"start_node,omitempty"`
	Relations     []string               `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"` // empty = all
	MaxDepth      int32                  `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	MinTrustState string                 `protobuf:"bytes,4,opt,name=min_trust_state,json=minTrustState,proto3" json:"min_trust_state,omitempty"`
	TraversalMode string                 `protobuf:"bytes,5,opt,name=traversal_mode,json=traversalMode,proto3" json:"traversal_mode,omitempty"` // bfs | dfs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraverseRequest) Reset() {
	*x = TraverseRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseRequest) ProtoMessage() {}

func (x *TraverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseRequest.ProtoReflect.Descriptor instead.
func (*TraverseRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{14}
}

func (x *TraverseRequest) GetStartNode() string {
	if x != nil {
		return x.StartNode
	}
	return ""
}

func (x *TraverseRequest) GetRelations() []string {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *TraverseRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *TraverseRequest) GetMinTrustState() string {
	if x != nil {
		return x.MinTrustState
	}
	return ""
}

func (x *TraverseRequest) GetTraversalMode() string {
	if x != nil {
		return x.TraversalMode
	}
	return ""
}

type PathSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         int32                  `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Edge          *GraphEdge             `protobuf:"bytes,2,opt,name=edge,proto3" json:"edge,omitempty"`
	Node          *GraphNode             `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathSegment) Reset() {
	*x = PathSegment{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSegment) ProtoMessage() {}

func (x *PathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSegment.ProtoReflect.Descriptor instead.
func (*PathSegment) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{15}
}

func (x *PathSegment) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PathSegment) GetEdge() *GraphEdge {
	if x != nil {
		return x.Edge
	}
	return nil
}

func (x *PathSegment) GetNode() *GraphNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type TraverseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []*PathSegment         `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraverseResponse) Reset() {
	*x = TraverseResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseResponse) ProtoMessage() {}

func (x *TraverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseResponse.ProtoReflect.Descriptor instead.
func (*TraverseResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{16}
}

func (x *TraverseResponse) GetPath() []*PathSegment {
	if x != nil {
		return x.Path
	}
	return nil
}

type ShortestPathRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromNode         string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode           string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	MinTrustState    string                 `protobuf:"bytes,3,opt,name=min_trust_state,json=minTrustState,proto3" json:"min_trust_state,omitempty"`
	AllowedRelations []string               `protobuf:"bytes,4,rep,name=allowed_relations,json=allowedRelations,proto3" json:"allowed_relations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShortestPathRequest) Reset() {
	*x = ShortestPathRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortestPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortestPathRequest) ProtoMessage() {}

func (x *ShortestPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortestPathRequest.ProtoReflect.Descriptor instead.
func (*ShortestPathRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{17}
}

func (x *ShortestPathRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *ShortestPathRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *ShortestPathRequest) GetMinTrustState() string {
	if x != nil {
		return x.MinTrustState
	}
	return ""
}

func (x *ShortestPathRequest) GetAllowedRelations() []string {
	if x != nil {
		return x.AllowedRelations
	}
	return nil
}

type ShortestPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*GraphEdge           `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	TotalWeight   float64                `protobuf:"fixed64,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortestPathResponse) Reset() {
	*x = ShortestPathResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortestPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortestPathResponse) ProtoMessage() {}

func (x *ShortestPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortestPathResponse.ProtoReflect.Descriptor instead.
func (*ShortestPathResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{18}
}

func (x *ShortestPathResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ShortestPathResponse) GetTotalWeight() float64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *ShortestPathResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ImpactRadiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	MinTrustState string                 `protobuf:"bytes,3,opt,name=min_trust_state,json=minTrustState,proto3" json:"min_trust_state,omitempty"`
	Relations     []string               `protobuf:"bytes,4,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactRadiusRequest) Reset() {
	*x = ImpactRadiusRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactRadiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactRadiusRequest) ProtoMessage() {}

func (x *ImpactRadiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactRadiusRequest.ProtoReflect.Descriptor instead.
func (*ImpactRadiusRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{19}
}

func (x *ImpactRadiusRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ImpactRadiusRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *ImpactRadiusRequest) GetMinTrustState() string {
	if x != nil {
		return x.MinTrustState
	}
	return ""
}

func (x *ImpactRadiusRequest) GetRelations() []string {
	if x != nil {
		return x.Relations
	}
	return nil
}

type ImpactRadiusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*GraphNode           `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactRadiusResponse) Reset() {
	*x = ImpactRadiusResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactRadiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactRadiusResponse) ProtoMessage() {}

func (x *ImpactRadiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactRadiusResponse.ProtoReflect.Descriptor instead.
func (*ImpactRadiusResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{20}
}

func (x *ImpactRadiusResponse) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ImpactRadiusResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ExplainClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainClaimRequest) Reset() {
	*x = ExplainClaimRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainClaimRequest) ProtoMessage() {}

func (x *ExplainClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainClaimRequest.ProtoReflect.Descriptor instead.
func (*ExplainClaimRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{21}
}

func (x *ExplainClaimRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *ExplainClaimRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type ExplainClaimResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Claim          *Claim                 `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	Evidence       []*Evidence            `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty"`
	ProofStateJson string                 `protobuf:"bytes,3,opt,name=proof_state_json,json=proofStateJson,proto3" json:"proof_state_json,omitempty"`
	TrustState     string                 `protobuf:"bytes,4,opt,name=trust_state,json=trustState,proto3" json:"trust_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExplainClaimResponse) Reset() {
	*x = ExplainClaimResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainClaimResponse) ProtoMessage() {}

func (x *ExplainClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainClaimResponse.ProtoReflect.Descriptor instead.
func (*ExplainClaimResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{22}
}

func (x *ExplainClaimResponse) GetClaim() *Claim {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *ExplainClaimResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ExplainClaimResponse) GetProofStateJson() string {
	if x != nil {
		return x.ProofStateJson
	}
	return ""
}

func (x *ExplainClaimResponse) GetTrustState() string {
	if x != nil {
		return x.TrustState
	}
	return ""
}

type ComputeTrustStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeTrustStateRequest) Reset() {
	*x = ComputeTrustStateRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeTrustStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeTrustStateRequest) ProtoMessage() {}

func (x *ComputeTrustStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeTrustStateRequest.ProtoReflect.Descriptor instead.
func (*ComputeTrustStateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{23}
}

func (x *ComputeTrustStateRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *ComputeTrustStateRequest) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

type ComputeTrustStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	ProofState    *ProofState            `protobuf:"bytes,3,opt,name=proof_state,json=proofState,proto3" json:"proof_state,omitempty"`
	TrustState    string                 `protobuf:"bytes,4,opt,name=trust_state,json=trustState,proto3" json:"trust_state,omitempty"`
	Diagnostics   []string               `protobuf:"bytes,5,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeTrustStateResponse) Reset() {
	*x = ComputeTrustStateResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeTrustStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeTrustStateResponse) ProtoMessage() {}

func (x *ComputeTrustStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeTrustStateResponse.ProtoReflect.Descriptor instead.
func (*ComputeTrustStateResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{24}
}

func (x *ComputeTrustStateResponse) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *ComputeTrustStateResponse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *ComputeTrustStateResponse) GetProofState() *ProofState {
	if x != nil {
		return x.ProofState
	}
	return nil
}

func (x *ComputeTrustStateResponse) GetTrustState() string {
	if x != nil {
		return x.TrustState
	}
	return ""
}

func (x *ComputeTrustStateResponse) GetDiagnostics() []string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type VerifyClosureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectNode   string                 `protobuf:"bytes,1,opt,name=subject_node,json=subjectNode,proto3" json:"subject_node,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClosureRequest) Reset() {
	*x = VerifyClosureRequest{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClosureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClosureRequest) ProtoMessage() {}

func (x *VerifyClosureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClosureRequest.ProtoReflect.Descriptor instead.
func (*VerifyClosureRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{25}
}

func (x *VerifyClosureRequest) GetSubjectNode() string {
	if x != nil {
		return x.SubjectNode
	}
	return ""
}

func (x *VerifyClosureRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *VerifyClosureRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

type VerifyClosureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectNode   string                 `protobuf:"bytes,1,opt,name=subject_node,json=subjectNode,proto3" json:"subject_node,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Verdict       bool                   `protobuf:"varint,3,opt,name=verdict,proto3" json:"verdict,omitempty"`
	TrustState    string                 `protobuf:"bytes,4,opt,name=trust_state,json=trustState,proto3" json:"trust_state,omitempty"`
	Diagnostics   []string               `protobuf:"bytes,5,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	EdgesChecked  int32                  `protobuf:"varint,6,opt,name=edges_checked,json=edgesChecked,proto3" json:"edges_checked,omitempty"`
	EdgesFailed   int32                  `protobuf:"varint,7,opt,name=edges_failed,json=edgesFailed,proto3" json:"edges_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClosureResponse) Reset() {
	*x = VerifyClosureResponse{}
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClosureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClosureResponse) ProtoMessage() {}

func (x *VerifyClosureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_transparency_graph_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClosureResponse.ProtoReflect.Descriptor instead.
func (*VerifyClosureResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_transparency_graph_service_proto_rawDescGZIP(), []int{26}
}

func (x *VerifyClosureResponse) GetSubjectNode() string {
	if x != nil {
		return x.SubjectNode
	}
	return ""
}

func (x *VerifyClosureResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *VerifyClosureResponse) GetVerdict() bool {
	if x != nil {
		return x.Verdict
	}
	return false
}

func (x *VerifyClosureResponse) GetTrustState() string {
	if x != nil {
		return x.TrustState
	}
	return ""
}

func (x *VerifyClosureResponse) GetDiagnostics() []string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *VerifyClosureResponse) GetEdgesChecked() int32 {
	if x != nil {
		return x.EdgesChecked
	}
	return 0
}

func (x *VerifyClosureResponse) GetEdgesFailed() int32 {
	if x != nil {
		return x.EdgesFailed
	}
	return 0
}

var File_services_v1_transparency_graph_service_proto protoreflect.FileDescriptor

const file_services_v1_transparency_graph_service_proto_rawDesc = "" +
	"\n" +
	",services/v1/transparency_graph_service.proto\x12\x11oscal.services.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a/services/v1/transparency_exchange_service.proto\"\x9d\x01\n" +
	"\tGraphNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x10\n" +
	"\x03urn\x18\x03 \x01(\tR\x03urn\x12\x1f\n" +
	"\vlabels_json\x18\x04 \x01(\tR\n" +
	"labelsJson\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaf\x03\n" +
	"\tGraphEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x1c\n" +
	"\tqualifier\x18\x05 \x01(\tR\tqualifier\x12\x19\n" +
	"\bclaim_id\x18\x06 \x01(\tR\aclaimId\x12'\n" +
	"\x0fevidence_digest\x18\a \x01(\tR\x0eevidenceDigest\x12>\n" +
	"\vproof_state\x18\b \x01(\v2\x1d.oscal.services.v1.ProofStateR\n" +
	"proofState\x12<\n" +
	"\n" +
	"valid_time\x18\t \x01(\v2\x1d.oscal.services.v1.TimeWindowR\tvalidTime\x12\x1f\n" +
	"\vtrust_state\x18\n" +
	" \x01(\tR\n" +
	"trustState\x12\x16\n" +
	"\x06weight\x18\v \x01(\x01R\x06weight\x12'\n" +
	"\x0fextensions_json\x18\f \x01(\tR\x0eextensionsJson\"H\n" +
	"\x12ProjectEdgeRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\"G\n" +
	"\x13ProjectEdgeResponse\x120\n" +
	"\x04edge\x18\x01 \x01(\v2\x1c.oscal.services.v1.GraphEdgeR\x04edge\")\n" +
	"\x0eGetEdgeRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\"C\n" +
	"\x0fGetEdgeResponse\x120\n" +
	"\x04edge\x18\x01 \x01(\v2\x1c.oscal.services.v1.GraphEdgeR\x04edge\"\xfe\x01\n" +
	"\x10ListEdgesRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1f\n" +
	"\vtrust_state\x18\x04 \x01(\tR\n" +
	"trustState\x12;\n" +
	"\vvalid_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validAfter\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\"o\n" +
	"\x11ListEdgesResponse\x122\n" +
	"\x05edges\x18\x01 \x03(\v2\x1c.oscal.services.v1.GraphEdgeR\x05edges\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\",\n" +
	"\x11DeleteEdgeRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\".\n" +
	"\x12DeleteEdgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"C\n" +
	"\x0fGetNodeResponse\x120\n" +
	"\x04node\x18\x01 \x01(\v2\x1c.oscal.services.v1.GraphNodeR\x04node\"\xc6\x01\n" +
	"\x10ListNodesRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\flabel_filter\x18\x02 \x01(\tR\vlabelFilter\x12?\n" +
	"\rcreated_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"o\n" +
	"\x11ListNodesResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.oscal.services.v1.GraphNodeR\x05nodes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xba\x01\n" +
	"\x0fTraverseRequest\x12\x1d\n" +
	"\n" +
	"start_node\x18\x01 \x01(\tR\tstartNode\x12\x1c\n" +
	"\trelations\x18\x02 \x03(\tR\trelations\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\x05R\bmaxDepth\x12&\n" +
	"\x0fmin_trust_state\x18\x04 \x01(\tR\rminTrustState\x12%\n" +
	"\x0etraversal_mode\x18\x05 \x01(\tR\rtraversalMode\"\x87\x01\n" +
	"\vPathSegment\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\x05R\x05depth\x120\n" +
	"\x04edge\x18\x02 \x01(\v2\x1c.oscal.services.v1.GraphEdgeR\x04edge\x120\n" +
	"\x04node\x18\x03 \x01(\v2\x1c.oscal.services.v1.GraphNodeR\x04node\"F\n" +
	"\x10TraverseResponse\x122\n" +
	"\x04path\x18\x01 \x03(\v2\x1e.oscal.services.v1.PathSegmentR\x04path\"\xa0\x01\n" +
	"\x13ShortestPathRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x12&\n" +
	"\x0fmin_trust_state\x18\x03 \x01(\tR\rminTrustState\x12+\n" +
	"\x11allowed_relations\x18\x04 \x03(\tR\x10allowedRelations\"\x83\x01\n" +
	"\x14ShortestPathResponse\x122\n" +
	"\x05edges\x18\x01 \x03(\v2\x1c.oscal.services.v1.GraphEdgeR\x05edges\x12!\n" +
	"\ftotal_weight\x18\x02 \x01(\x01R\vtotalWeight\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"\x8c\x01\n" +
	"\x13ImpactRadiusRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\x12&\n" +
	"\x0fmin_trust_state\x18\x03 \x01(\tR\rminTrustState\x12\x1c\n" +
	"\trelations\x18\x04 \x03(\tR\trelations\"~\n" +
	"\x14ImpactRadiusResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.oscal.services.v1.GraphNodeR\x05nodes\x122\n" +
	"\x05edges\x18\x02 \x03(\v2\x1c.oscal.services.v1.GraphEdgeR\x05edges\"I\n" +
	"\x13ExplainClaimRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\"\xca\x01\n" +
	"\x14ExplainClaimResponse\x12.\n" +
	"\x05claim\x18\x01 \x01(\v2\x18.oscal.services.v1.ClaimR\x05claim\x127\n" +
	"\bevidence\x18\x02 \x03(\v2\x1b.oscal.services.v1.EvidenceR\bevidence\x12(\n" +
	"\x10proof_state_json\x18\x03 \x01(\tR\x0eproofStateJson\x12\x1f\n" +
	"\vtrust_state\x18\x04 \x01(\tR\n" +
	"trustState\"N\n" +
	"\x18ComputeTrustStateRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\"\xd2\x01\n" +
	"\x19ComputeTrustStateResponse\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12>\n" +
	"\vproof_state\x18\x03 \x01(\v2\x1d.oscal.services.v1.ProofStateR\n" +
	"proofState\x12\x1f\n" +
	"\vtrust_state\x18\x04 \x01(\tR\n" +
	"trustState\x12 \n" +
	"\vdiagnostics\x18\x05 \x03(\tR\vdiagnostics\"\x84\x01\n" +
	"\x14VerifyClosureRequest\x12!\n" +
	"\fsubject_node\x18\x01 \x01(\tR\vsubjectNode\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12/\n" +
	"\x05as_of\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\"\xf9\x01\n" +
	"\x15VerifyClosureResponse\x12!\n" +
	"\fsubject_node\x18\x01 \x01(\tR\vsubjectNode\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x18\n" +
	"\averdict\x18\x03 \x01(\bR\averdict\x12\x1f\n" +
	"\vtrust_state\x18\x04 \x01(\tR\n" +
	"trustState\x12 \n" +
	"\vdiagnostics\x18\x05 \x03(\tR\vdiagnostics\x12#\n" +
	"\redges_checked\x18\x06 \x01(\x05R\fedgesChecked\x12!\n" +
	"\fedges_failed\x18\a \x01(\x05R\vedgesFailed2\xfa\v\n" +
	"\x18TransparencyGraphService\x12x\n" +
	"\vProjectEdge\x12%.oscal.services.v1.ProjectEdgeRequest\x1a&.oscal.services.v1.ProjectEdgeResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/graph/edges\x12s\n" +
	"\aGetEdge\x12!.oscal.services.v1.GetEdgeRequest\x1a\".oscal.services.v1.GetEdgeResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/graph/edges/{edge_id}\x12o\n" +
	"\tListEdges\x12#.oscal.services.v1.ListEdgesRequest\x1a$.oscal.services.v1.ListEdgesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/graph/edges\x12|\n" +
	"\n" +
	"DeleteEdge\x12$.oscal.services.v1.DeleteEdgeRequest\x1a%.oscal.services.v1.DeleteEdgeResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/graph/edges/{edge_id}\x12s\n" +
	"\aGetNode\x12!.oscal.services.v1.GetNodeRequest\x1a\".oscal.services.v1.GetNodeResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/graph/nodes/{node_id}\x12o\n" +
	"\tListNodes\x12#.oscal.services.v1.ListNodesRequest\x1a$.oscal.services.v1.ListNodesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/graph/nodes\x12r\n" +
	"\bTraverse\x12\".oscal.services.v1.TraverseRequest\x1a#.oscal.services.v1.TraverseResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/graph/traverse\x12\x83\x01\n" +
	"\fShortestPath\x12&.oscal.services.v1.ShortestPathRequest\x1a'.oscal.services.v1.ShortestPathResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/graph/shortest-path\x12\x83\x01\n" +
	"\fImpactRadius\x12&.oscal.services.v1.ImpactRadiusRequest\x1a'.oscal.services.v1.ImpactRadiusResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/graph/impact-radius\x12}\n" +
	"\fExplainClaim\x12&.oscal.services.v1.ExplainClaimRequest\x1a'.oscal.services.v1.ExplainClaimResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/graph/explain\x12\x90\x01\n" +
	"\x11ComputeTrustState\x12+.oscal.services.v1.ComputeTrustStateRequest\x1a,.oscal.services.v1.ComputeTrustStateResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/graph/trust-state\x12\x87\x01\n" +
	"\rVerifyClosure\x12'.oscal.services.v1.VerifyClosureRequest\x1a(.oscal.services.v1.VerifyClosureResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/graph/verify-closureB>Z<github.com/mchorfa/xoscal/proto/oscal/services/v1;servicesv1b\x06proto3"

var (
	file_services_v1_transparency_graph_service_proto_rawDescOnce sync.Once
	file_services_v1_transparency_graph_service_proto_rawDescData []byte
)

func file_services_v1_transparency_graph_service_proto_rawDescGZIP() []byte {
	file_services_v1_transparency_graph_service_proto_rawDescOnce.Do(func() {
		file_services_v1_transparency_graph_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_v1_transparency_graph_service_proto_rawDesc), len(file_services_v1_transparency_graph_service_proto_rawDesc)))
	})
	return file_services_v1_transparency_graph_service_proto_rawDescData
}

var file_services_v1_transparency_graph_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_services_v1_transparency_graph_service_proto_goTypes = []any{
	(*GraphNode)(nil),                 // 0: oscal.services.v1.GraphNode
	(*GraphEdge)(nil),                 // 1: oscal.services.v1.GraphEdge
	(*ProjectEdgeRequest)(nil),        // 2: oscal.services.v1.ProjectEdgeRequest
	(*ProjectEdgeResponse)(nil),       // 3: oscal.services.v1.ProjectEdgeResponse
	(*GetEdgeRequest)(nil),            // 4: oscal.services.v1.GetEdgeRequest
	(*GetEdgeResponse)(nil),           // 5: oscal.services.v1.GetEdgeResponse
	(*ListEdgesRequest)(nil),          // 6: oscal.services.v1.ListEdgesRequest
	(*ListEdgesResponse)(nil),         // 7: oscal.services.v1.ListEdgesResponse
	(*DeleteEdgeRequest)(nil),         // 8: oscal.services.v1.DeleteEdgeRequest
	(*DeleteEdgeResponse)(nil),        // 9: oscal.services.v1.DeleteEdgeResponse
	(*GetNodeRequest)(nil),            // 10: oscal.services.v1.GetNodeRequest
	(*GetNodeResponse)(nil),           // 11: oscal.services.v1.GetNodeResponse
	(*ListNodesRequest)(nil),          // 12: oscal.services.v1.ListNodesRequest
	(*ListNodesResponse)(nil),         // 13: oscal.services.v1.ListNodesResponse
	(*TraverseRequest)(nil),           // 14: oscal.services.v1.TraverseRequest
	(*PathSegment)(nil),               // 15: oscal.services.v1.PathSegment
	(*TraverseResponse)(nil),          // 16: oscal.services.v1.TraverseResponse
	(*ShortestPathRequest)(nil),       // 17: oscal.services.v1.ShortestPathRequest
	(*ShortestPathResponse)(nil),      // 18: oscal.services.v1.ShortestPathResponse
	(*ImpactRadiusRequest)(nil),       // 19: oscal.services.v1.ImpactRadiusRequest
	(*ImpactRadiusResponse)(nil),      // 20: oscal.services.v1.ImpactRadiusResponse
	(*ExplainClaimRequest)(nil),       // 21: oscal.services.v1.ExplainClaimRequest
	(*ExplainClaimResponse)(nil),      // 22: oscal.services.v1.ExplainClaimResponse
	(*ComputeTrustStateRequest)(nil),  // 23: oscal.services.v1.ComputeTrustStateRequest
	(*ComputeTrustStateResponse)(nil), // 24: oscal.services.v1.ComputeTrustStateResponse
	(*VerifyClosureRequest)(nil),      // 25: oscal.services.v1.VerifyClosureRequest
	(*VerifyClosureResponse)(nil),     // 26: oscal.services.v1.VerifyClosureResponse
	(*timestamppb.Timestamp)(nil),     // 27: google.protobuf.Timestamp
	(*ProofState)(nil),                // 28: oscal.services.v1.ProofState
	(*TimeWindow)(nil),                // 29: oscal.services.v1.TimeWindow
	(*Claim)(nil),                     // 30: oscal.services.v1.Claim
	(*Evidence)(nil),                  // 31: oscal.services.v1.Evidence
}
var file_services_v1_transparency_graph_service_proto_depIdxs = []int32{
	27, // 0: oscal.services.v1.GraphNode.created_at:type_name -> google.protobuf.Timestamp
	28, // 1: oscal.services.v1.GraphEdge.proof_state:type_name -> oscal.services.v1.ProofState
	29, // 2: oscal.services.v1.GraphEdge.valid_time:type_name -> oscal.services.v1.TimeWindow
	1,  // 3: oscal.services.v1.ProjectEdgeResponse.edge:type_name -> oscal.services.v1.GraphEdge
	1,  // 4: oscal.services.v1.GetEdgeResponse.edge:type_name -> oscal.services.v1.GraphEdge
	27, // 5: oscal.services.v1.ListEdgesRequest.valid_after:type_name -> google.protobuf.Timestamp
	1,  // 6: oscal.services.v1.ListEdgesResponse.edges:type_name -> oscal.services.v1.GraphEdge
	0,  // 7: oscal.services.v1.GetNodeResponse.node:type_name -> oscal.services.v1.GraphNode
	27, // 8: oscal.services.v1.ListNodesRequest.created_after:type_name -> google.protobuf.Timestamp
	0,  // 9: oscal.services.v1.ListNodesResponse.nodes:type_name -> oscal.services.v1.GraphNode
	1,  // 10: oscal.services.v1.PathSegment.edge:type_name -> oscal.services.v1.GraphEdge
	0,  // 11: oscal.services.v1.PathSegment.node:type_name -> oscal.services.v1.GraphNode
	15, // 12: oscal.services.v1.TraverseResponse.path:type_name -> oscal.services.v1.PathSegment
	1,  // 13: oscal.services.v1.ShortestPathResponse.edges:type_name -> oscal.services.v1.GraphEdge
	0,  // 14: oscal.services.v1.ImpactRadiusResponse.nodes:type_name -> oscal.services.v1.GraphNode
	1,  // 15: oscal.services.v1.ImpactRadiusResponse.edges:type_name -> oscal.services.v1.GraphEdge
	30, // 16: oscal.services.v1.ExplainClaimResponse.claim:type_name -> oscal.services.v1.Claim
	31, // 17: oscal.services.v1.ExplainClaimResponse.evidence:type_name -> oscal.services.v1.Evidence
	28, // 18: oscal.services.v1.ComputeTrustStateResponse.proof_state:type_name -> oscal.services.v1.ProofState
	27, // 19: oscal.services.v1.VerifyClosureRequest.as_of:type_name -> google.protobuf.Timestamp
	2,  // 20: oscal.services.v1.TransparencyGraphService.ProjectEdge:input_type -> oscal.services.v1.ProjectEdgeRequest
	4,  // 21: oscal.services.v1.TransparencyGraphService.GetEdge:input_type -> oscal.services.v1.GetEdgeRequest
	6,  // 22: oscal.services.v1.TransparencyGraphService.ListEdges:input_type -> oscal.services.v1.ListEdgesRequest
	8,  // 23: oscal.services.v1.TransparencyGraphService.DeleteEdge:input_type -> oscal.services.v1.DeleteEdgeRequest
	10, // 24: oscal.services.v1.TransparencyGraphService.GetNode:input_type -> oscal.services.v1.GetNodeRequest
	12, // 25: oscal.services.v1.TransparencyGraphService.ListNodes:input_type -> oscal.services.v1.ListNodesRequest
	14, // 26: oscal.services.v1.TransparencyGraphService.Traverse:input_type -> oscal.services.v1.TraverseRequest
	17, // 27: oscal.services.v1.TransparencyGraphService.ShortestPath:input_type -> oscal.services.v1.ShortestPathRequest
	19, // 28: oscal.services.v1.TransparencyGraphService.ImpactRadius:input_type -> oscal.services.v1.ImpactRadiusRequest
	21, // 29: oscal.services.v1.TransparencyGraphService.ExplainClaim:input_type -> oscal.services.v1.ExplainClaimRequest
	23, // 30: oscal.services.v1.TransparencyGraphService.ComputeTrustState:input_type -> oscal.services.v1.ComputeTrustStateRequest
	25, // 31: oscal.services.v1.TransparencyGraphService.VerifyClosure:input_type -> oscal.services.v1.VerifyClosureRequest
	3,  // 32: oscal.services.v1.TransparencyGraphService.ProjectEdge:output_type -> oscal.services.v1.ProjectEdgeResponse
	5,  // 33: oscal.services.v1.TransparencyGraphService.GetEdge:output_type -> oscal.services.v1.GetEdgeResponse
	7,  // 34: oscal.services.v1.TransparencyGraphService.ListEdges:output_type -> oscal.services.v1.ListEdgesResponse
	9,  // 35: oscal.services.v1.TransparencyGraphService.DeleteEdge:output_type -> oscal.services.v1.DeleteEdgeResponse
	11, // 36: oscal.services.v1.TransparencyGraphService.GetNode:output_type -> oscal.services.v1.GetNodeResponse
	13, // 37: oscal.services.v1.TransparencyGraphService.ListNodes:output_type -> oscal.services.v1.ListNodesResponse
	16, // 38: oscal.services.v1.TransparencyGraphService.Traverse:output_type -> oscal.services.v1.TraverseResponse
	18, // 39: oscal.services.v1.TransparencyGraphService.ShortestPath:output_type -> oscal.services.v1.ShortestPathResponse
	20, // 40: oscal.services.v1.TransparencyGraphService.ImpactRadius:output_type -> oscal.services.v1.ImpactRadiusResponse
	22, // 41: oscal.services.v1.TransparencyGraphService.ExplainClaim:output_type -> oscal.services.v1.ExplainClaimResponse
	24, // 42: oscal.services.v1.TransparencyGraphService.ComputeTrustState:output_type -> oscal.services.v1.ComputeTrustStateResponse
	26, // 43: oscal.services.v1.TransparencyGraphService.VerifyClosure:output_type -> oscal.services.v1.VerifyClosureResponse
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_services_v1_transparency_graph_service_proto_init() }
func file_services_v1_transparency_graph_service_proto_init() {
	if File_services_v1_transparency_graph_service_proto != nil {
		return
	}
	file_services_v1_transparency_exchange_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_v1_transparency_graph_service_proto_rawDesc), len(file_services_v1_transparency_graph_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_transparency_graph_service_proto_goTypes,
		DependencyIndexes: file_services_v1_transparency_graph_service_proto_depIdxs,
		MessageInfos:      file_services_v1_transparency_graph_service_proto_msgTypes,
	}.Build()
	File_services_v1_transparency_graph_service_proto = out.File
	file_services_v1_transparency_graph_service_proto_goTypes = nil
	file_services_v1_transparency_graph_service_proto_depIdxs = nil
}
