package main

import "dagger/xoscal/internal/dagger"

// siteShell vendors exact presentation assets. No mutable release lookups or
// signing decisions belong to presentation assembly.
func (m *Xoscal) siteShell(source *dagger.Directory) *dagger.Container {
	frontend := m.FrontendAssets(source)
	return m.toolBase().WithDirectory("/src", source).WithWorkdir("/src").
		WithDirectory("/out", source.Directory("site")).
		WithDirectory("/out/assets/badges", m.Badges(source)).
		WithFile("/out/scripts/install.sh", source.File("scripts/install.sh")).
		WithDirectory("/out/evidence/frontend", frontend).
		WithDirectory("/out/evidence/frontend-sbom", m.SbomArtifactAnalysis(source, frontend.File("sbom.cyclonedx.json"))).
		WithFile("/out/scalar.js", frontend.File("scalar.js")).
		WithFile("/out/scalar.js.map", frontend.File("scalar.js.map")).
		WithFile("/out/scalar.css", frontend.File("scalar.css")).
		WithFile("/out/scalar.css.map", frontend.File("scalar.css.map")).
		WithFile("/out/THIRD-PARTY-NOTICES.txt", frontend.File("THIRD-PARTY-NOTICES.txt")).
		WithFile("/tools/render_api_reference.py", dag.CurrentModule().Source().File("render_api_reference.py")).
		WithExec([]string{"python3", "scripts/render-blueprint.py", "--output", "/out/portal.html"})
}

// sitePayload assembles unsigned preview bytes before presentation admission.
func (m *Xoscal) sitePayload(source *dagger.Directory) *dagger.Directory {
	c := m.siteShell(source).
		WithDirectory("/out/sdk", m.SdkBundles(source)).
		WithDirectory("/out/frameworks", m.OscalFrameworks(source)).
		WithFile("/out/openapi.json", m.Openapi(source)).
		WithExec([]string{"python3", "/tools/render_api_reference.py", "--root", "/out"}).
		WithFile("/out/sbom-assessment-results.json", m.SbomValidationReports(source, m.Sbom(source)).File("sbom-assessment-results.oscal.json")).
		WithExec([]string{"sh", "-c", "revision=$(git rev-parse HEAD); python3 scripts/release-contract.py create --root /out --tag dev --revision \"$revision\""}).
		WithExec([]string{"python3", "scripts/render-release-site.py", "--root", "/out", "--manifest", "/out/payload-manifest.json"}).
		WithExec([]string{"python3", "scripts/site-smoke.py", "--root", "/out", "--generated"}).
		Directory("/out")
	return c
}

// Site builds a complete admitted unsigned local preview. Only FinalizeCandidate
// may render eligibility after verifying a hosted payload attestation.
func (m *Xoscal) Site(source *dagger.Directory) *dagger.Directory {
	return m.PresentationAnalysis(source, m.sitePayload(source)).Directory("/src/site")
}

// SitePresentationReports preserves exact unadmitted payloads and raw browser
// failures for diagnosis. Export success never admits or signs these bytes.
func (m *Xoscal) SitePresentationReports(source *dagger.Directory) *dagger.Directory {
	payload := m.sitePayload(source)
	return dag.Directory().WithDirectory("payload", payload).
		WithDirectory("reports", m.PresentationBrowserReports(source, payload))
}

// Serve previews actual generated bytes, explicitly without hosted proof.
func (m *Xoscal) Serve(source *dagger.Directory) *dagger.Service {
	return dag.Container().From("python:3.13-alpine").
		WithDirectory("/site", m.Site(source)).WithWorkdir("/site").
		WithExposedPort(8080).AsService(dagger.ContainerAsServiceOpts{
		Args: []string{"python", "-m", "http.server", "8080"},
	})
}
