// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: assessment_plan/v1/assessment_plan.proto

package assessment_planv1

import (
	v1 "github.com/mchorfa/xoscal/proto/oscal/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssessmentPlan represents a security assessment plan
type AssessmentPlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Metadata         *v1.Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ImportSsp        *ImportSsp             `protobuf:"bytes,3,opt,name=import_ssp,json=importSsp,proto3" json:"import_ssp,omitempty"`
	LocalDefinitions *LocalDefinitions      `protobuf:"bytes,4,opt,name=local_definitions,json=localDefinitions,proto3" json:"local_definitions,omitempty"`
	Terms            *Terms                 `protobuf:"bytes,5,opt,name=terms,proto3" json:"terms,omitempty"`
	ReviewedControls *ReviewedControls      `protobuf:"bytes,6,opt,name=reviewed_controls,json=reviewedControls,proto3" json:"reviewed_controls,omitempty"`
	AssessmentTasks  []*AssessmentTask      `protobuf:"bytes,7,rep,name=assessment_tasks,json=assessmentTasks,proto3" json:"assessment_tasks,omitempty"`
	BackMatter       *v1.BackMatter         `protobuf:"bytes,8,opt,name=back_matter,json=backMatter,proto3" json:"back_matter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssessmentPlan) Reset() {
	*x = AssessmentPlan{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentPlan) ProtoMessage() {}

func (x *AssessmentPlan) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentPlan.ProtoReflect.Descriptor instead.
func (*AssessmentPlan) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{0}
}

func (x *AssessmentPlan) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *AssessmentPlan) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AssessmentPlan) GetImportSsp() *ImportSsp {
	if x != nil {
		return x.ImportSsp
	}
	return nil
}

func (x *AssessmentPlan) GetLocalDefinitions() *LocalDefinitions {
	if x != nil {
		return x.LocalDefinitions
	}
	return nil
}

func (x *AssessmentPlan) GetTerms() *Terms {
	if x != nil {
		return x.Terms
	}
	return nil
}

func (x *AssessmentPlan) GetReviewedControls() *ReviewedControls {
	if x != nil {
		return x.ReviewedControls
	}
	return nil
}

func (x *AssessmentPlan) GetAssessmentTasks() []*AssessmentTask {
	if x != nil {
		return x.AssessmentTasks
	}
	return nil
}

func (x *AssessmentPlan) GetBackMatter() *v1.BackMatter {
	if x != nil {
		return x.BackMatter
	}
	return nil
}

// ImportSsp represents an imported system security plan
type ImportSsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          *v1.URIReference       `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSsp) Reset() {
	*x = ImportSsp{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSsp) ProtoMessage() {}

func (x *ImportSsp) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSsp.ProtoReflect.Descriptor instead.
func (*ImportSsp) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{1}
}

func (x *ImportSsp) GetHref() *v1.URIReference {
	if x != nil {
		return x.Href
	}
	return nil
}

func (x *ImportSsp) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// LocalDefinitions represents local definitions for the assessment plan
type LocalDefinitions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Components     []*Component           `protobuf:"bytes,1,rep,name=components,proto3" json:"components,omitempty"`
	InventoryItems []*InventoryItem       `protobuf:"bytes,2,rep,name=inventory_items,json=inventoryItems,proto3" json:"inventory_items,omitempty"`
	Users          []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Objectives     []*LocalObjective      `protobuf:"bytes,4,rep,name=objectives,proto3" json:"objectives,omitempty"`
	Methods        []*AssessmentMethod    `protobuf:"bytes,5,rep,name=methods,proto3" json:"methods,omitempty"`
	Activities     []*Activity            `protobuf:"bytes,6,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalDefinitions) Reset() {
	*x = LocalDefinitions{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDefinitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDefinitions) ProtoMessage() {}

func (x *LocalDefinitions) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDefinitions.ProtoReflect.Descriptor instead.
func (*LocalDefinitions) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{2}
}

func (x *LocalDefinitions) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *LocalDefinitions) GetInventoryItems() []*InventoryItem {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

func (x *LocalDefinitions) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *LocalDefinitions) GetObjectives() []*LocalObjective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *LocalDefinitions) GetMethods() []*AssessmentMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *LocalDefinitions) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

// Component represents a system component
type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,7,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{3}
}

func (x *Component) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Component) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Component) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Component) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Component) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Component) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Component) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// InventoryItem represents an inventory item
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Description   *v1.MarkupLine         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryItem) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *InventoryItem) GetDescription() *v1.MarkupLine {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *InventoryItem) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *InventoryItem) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *InventoryItem) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// User represents a system user
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ShortName     string                 `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,7,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *User) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *User) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *User) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *User) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *User) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *User) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// LocalObjective represents a local control objective
type LocalObjective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlId     *v1.Token              `protobuf:"bytes,1,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Parts         []*Part                `protobuf:"bytes,5,rep,name=parts,proto3" json:"parts,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,6,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalObjective) Reset() {
	*x = LocalObjective{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalObjective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalObjective) ProtoMessage() {}

func (x *LocalObjective) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalObjective.ProtoReflect.Descriptor instead.
func (*LocalObjective) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{6}
}

func (x *LocalObjective) GetControlId() *v1.Token {
	if x != nil {
		return x.ControlId
	}
	return nil
}

func (x *LocalObjective) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *LocalObjective) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *LocalObjective) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *LocalObjective) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *LocalObjective) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Part represents a part of an objective
type Part struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.Token              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ns            string                 `protobuf:"bytes,3,opt,name=ns,proto3" json:"ns,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,6,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,7,rep,name=links,proto3" json:"links,omitempty"`
	Parts         []*Part                `protobuf:"bytes,8,rep,name=parts,proto3" json:"parts,omitempty"`
	Prose         []*v1.MarkupMultiline  `protobuf:"bytes,9,rep,name=prose,proto3" json:"prose,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,10,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{7}
}

func (x *Part) GetId() *v1.Token {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Part) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Part) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Part) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Part) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Part) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Part) GetProse() []*v1.MarkupMultiline {
	if x != nil {
		return x.Prose
	}
	return nil
}

func (x *Part) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// AssessmentMethod represents an assessment method
type AssessmentMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Part          *AssessmentPart        `protobuf:"bytes,5,opt,name=part,proto3" json:"part,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,6,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentMethod) Reset() {
	*x = AssessmentMethod{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentMethod) ProtoMessage() {}

func (x *AssessmentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentMethod.ProtoReflect.Descriptor instead.
func (*AssessmentMethod) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{8}
}

func (x *AssessmentMethod) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *AssessmentMethod) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *AssessmentMethod) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *AssessmentMethod) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *AssessmentMethod) GetPart() *AssessmentPart {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *AssessmentMethod) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// AssessmentPart represents an assessment part
type AssessmentPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.Token              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ns            string                 `protobuf:"bytes,3,opt,name=ns,proto3" json:"ns,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,6,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,7,rep,name=links,proto3" json:"links,omitempty"`
	Parts         []*AssessmentPart      `protobuf:"bytes,8,rep,name=parts,proto3" json:"parts,omitempty"`
	Prose         []*v1.MarkupMultiline  `protobuf:"bytes,9,rep,name=prose,proto3" json:"prose,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,10,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentPart) Reset() {
	*x = AssessmentPart{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentPart) ProtoMessage() {}

func (x *AssessmentPart) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentPart.ProtoReflect.Descriptor instead.
func (*AssessmentPart) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{9}
}

func (x *AssessmentPart) GetId() *v1.Token {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AssessmentPart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssessmentPart) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *AssessmentPart) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *AssessmentPart) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *AssessmentPart) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *AssessmentPart) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *AssessmentPart) GetParts() []*AssessmentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *AssessmentPart) GetProse() []*v1.MarkupMultiline {
	if x != nil {
		return x.Prose
	}
	return nil
}

func (x *AssessmentPart) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Activity represents an assessment activity
type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	Steps         []*Step                `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,7,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{10}
}

func (x *Activity) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Activity) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Activity) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Activity) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Activity) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Activity) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Activity) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Step represents a step in an activity
type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,6,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{11}
}

func (x *Step) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Step) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Step) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Step) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Step) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Step) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Terms represents assessment plan terms
type Terms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terms         []*Term                `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Terms) Reset() {
	*x = Terms{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terms) ProtoMessage() {}

func (x *Terms) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terms.ProtoReflect.Descriptor instead.
func (*Terms) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{12}
}

func (x *Terms) GetTerms() []*Term {
	if x != nil {
		return x.Terms
	}
	return nil
}

// Term represents a defined term
type Term struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.Token              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *v1.MarkupLine         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Definition    *v1.MarkupMultiline    `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,6,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Term) Reset() {
	*x = Term{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Term) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term) ProtoMessage() {}

func (x *Term) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term.ProtoReflect.Descriptor instead.
func (*Term) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{13}
}

func (x *Term) GetId() *v1.Token {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Term) GetName() *v1.MarkupLine {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Term) GetDefinition() *v1.MarkupMultiline {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Term) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Term) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Term) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// ReviewedControls represents reviewed controls
type ReviewedControls struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ControlSelection string                 `protobuf:"bytes,1,opt,name=control_selection,json=controlSelection,proto3" json:"control_selection,omitempty"`
	Controls         []*ControlSelection    `protobuf:"bytes,2,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReviewedControls) Reset() {
	*x = ReviewedControls{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewedControls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewedControls) ProtoMessage() {}

func (x *ReviewedControls) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewedControls.ProtoReflect.Descriptor instead.
func (*ReviewedControls) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{14}
}

func (x *ReviewedControls) GetControlSelection() string {
	if x != nil {
		return x.ControlSelection
	}
	return ""
}

func (x *ReviewedControls) GetControls() []*ControlSelection {
	if x != nil {
		return x.Controls
	}
	return nil
}

// ControlSelection represents a control selection
type ControlSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlId     *v1.Token              `protobuf:"bytes,1,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlSelection) Reset() {
	*x = ControlSelection{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlSelection) ProtoMessage() {}

func (x *ControlSelection) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlSelection.ProtoReflect.Descriptor instead.
func (*ControlSelection) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{15}
}

func (x *ControlSelection) GetControlId() *v1.Token {
	if x != nil {
		return x.ControlId
	}
	return nil
}

func (x *ControlSelection) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// AssessmentTask represents an assessment task
type AssessmentTask struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Uuid                 *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                *v1.MarkupLine         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          *v1.MarkupMultiline    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Subjects             []*SubjectReference    `protobuf:"bytes,5,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Tasks                []*Task                `protobuf:"bytes,6,rep,name=tasks,proto3" json:"tasks,omitempty"`
	AssociatedActivities []*AssociatedActivity  `protobuf:"bytes,7,rep,name=associated_activities,json=associatedActivities,proto3" json:"associated_activities,omitempty"`
	ResponsibleRoles     []*ResponsibleRole     `protobuf:"bytes,8,rep,name=responsible_roles,json=responsibleRoles,proto3" json:"responsible_roles,omitempty"`
	Props                []*v1.Property         `protobuf:"bytes,9,rep,name=props,proto3" json:"props,omitempty"`
	Links                []*v1.Link             `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Remarks              []*v1.MarkupMultiline  `protobuf:"bytes,11,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AssessmentTask) Reset() {
	*x = AssessmentTask{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentTask) ProtoMessage() {}

func (x *AssessmentTask) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentTask.ProtoReflect.Descriptor instead.
func (*AssessmentTask) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{16}
}

func (x *AssessmentTask) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *AssessmentTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AssessmentTask) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *AssessmentTask) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *AssessmentTask) GetSubjects() []*SubjectReference {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *AssessmentTask) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *AssessmentTask) GetAssociatedActivities() []*AssociatedActivity {
	if x != nil {
		return x.AssociatedActivities
	}
	return nil
}

func (x *AssessmentTask) GetResponsibleRoles() []*ResponsibleRole {
	if x != nil {
		return x.ResponsibleRoles
	}
	return nil
}

func (x *AssessmentTask) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *AssessmentTask) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *AssessmentTask) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// SubjectReference represents a subject reference
type SubjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectUuid   *v1.UUID               `protobuf:"bytes,1,opt,name=subject_uuid,json=subjectUuid,proto3" json:"subject_uuid,omitempty"`
	Title         *v1.MarkupLine         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectReference) Reset() {
	*x = SubjectReference{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectReference) ProtoMessage() {}

func (x *SubjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectReference.ProtoReflect.Descriptor instead.
func (*SubjectReference) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{17}
}

func (x *SubjectReference) GetSubjectUuid() *v1.UUID {
	if x != nil {
		return x.SubjectUuid
	}
	return nil
}

func (x *SubjectReference) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SubjectReference) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *SubjectReference) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *SubjectReference) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Task represents a sub-task
type Task struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Uuid                 *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                *v1.MarkupLine         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          *v1.MarkupMultiline    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Subjects             []*SubjectReference    `protobuf:"bytes,5,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Tasks                []*Task                `protobuf:"bytes,6,rep,name=tasks,proto3" json:"tasks,omitempty"`
	AssociatedActivities []*AssociatedActivity  `protobuf:"bytes,7,rep,name=associated_activities,json=associatedActivities,proto3" json:"associated_activities,omitempty"`
	ResponsibleRoles     []*ResponsibleRole     `protobuf:"bytes,8,rep,name=responsible_roles,json=responsibleRoles,proto3" json:"responsible_roles,omitempty"`
	Props                []*v1.Property         `protobuf:"bytes,9,rep,name=props,proto3" json:"props,omitempty"`
	Links                []*v1.Link             `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Remarks              []*v1.MarkupMultiline  `protobuf:"bytes,11,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{18}
}

func (x *Task) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetTitle() *v1.MarkupLine {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Task) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Task) GetSubjects() []*SubjectReference {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Task) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Task) GetAssociatedActivities() []*AssociatedActivity {
	if x != nil {
		return x.AssociatedActivities
	}
	return nil
}

func (x *Task) GetResponsibleRoles() []*ResponsibleRole {
	if x != nil {
		return x.ResponsibleRoles
	}
	return nil
}

func (x *Task) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Task) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Task) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// AssociatedActivity represents an associated activity
type AssociatedActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityUuid  *v1.UUID               `protobuf:"bytes,1,opt,name=activity_uuid,json=activityUuid,proto3" json:"activity_uuid,omitempty"`
	IncludeAll    bool                   `protobuf:"varint,2,opt,name=include_all,json=includeAll,proto3" json:"include_all,omitempty"`
	ActivityUuids []*v1.UUID             `protobuf:"bytes,3,rep,name=activity_uuids,json=activityUuids,proto3" json:"activity_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociatedActivity) Reset() {
	*x = AssociatedActivity{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociatedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociatedActivity) ProtoMessage() {}

func (x *AssociatedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociatedActivity.ProtoReflect.Descriptor instead.
func (*AssociatedActivity) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{19}
}

func (x *AssociatedActivity) GetActivityUuid() *v1.UUID {
	if x != nil {
		return x.ActivityUuid
	}
	return nil
}

func (x *AssociatedActivity) GetIncludeAll() bool {
	if x != nil {
		return x.IncludeAll
	}
	return false
}

func (x *AssociatedActivity) GetActivityUuids() []*v1.UUID {
	if x != nil {
		return x.ActivityUuids
	}
	return nil
}

// ResponsibleRole represents a responsible role
type ResponsibleRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        *v1.Token              `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PartyUuids    []*v1.UUID             `protobuf:"bytes,2,rep,name=party_uuids,json=partyUuids,proto3" json:"party_uuids,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,4,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsibleRole) Reset() {
	*x = ResponsibleRole{}
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsibleRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsibleRole) ProtoMessage() {}

func (x *ResponsibleRole) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_plan_v1_assessment_plan_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsibleRole.ProtoReflect.Descriptor instead.
func (*ResponsibleRole) Descriptor() ([]byte, []int) {
	return file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP(), []int{20}
}

func (x *ResponsibleRole) GetRoleId() *v1.Token {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *ResponsibleRole) GetPartyUuids() []*v1.UUID {
	if x != nil {
		return x.PartyUuids
	}
	return nil
}

func (x *ResponsibleRole) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *ResponsibleRole) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

var File_assessment_plan_v1_assessment_plan_proto protoreflect.FileDescriptor

const file_assessment_plan_v1_assessment_plan_proto_rawDesc = "" +
	"\n" +
	"(assessment_plan/v1/assessment_plan.proto\x12\x18oscal.assessment_plan.v1\x1a\x16common/v1/common.proto\"\xb2\x04\n" +
	"\x0eAssessmentPlan\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.oscal.common.v1.MetadataR\bmetadata\x12B\n" +
	"\n" +
	"import_ssp\x18\x03 \x01(\v2#.oscal.assessment_plan.v1.ImportSspR\timportSsp\x12W\n" +
	"\x11local_definitions\x18\x04 \x01(\v2*.oscal.assessment_plan.v1.LocalDefinitionsR\x10localDefinitions\x125\n" +
	"\x05terms\x18\x05 \x01(\v2\x1f.oscal.assessment_plan.v1.TermsR\x05terms\x12W\n" +
	"\x11reviewed_controls\x18\x06 \x01(\v2*.oscal.assessment_plan.v1.ReviewedControlsR\x10reviewedControls\x12S\n" +
	"\x10assessment_tasks\x18\a \x03(\v2(.oscal.assessment_plan.v1.AssessmentTaskR\x0fassessmentTasks\x12<\n" +
	"\vback_matter\x18\b \x01(\v2\x1b.oscal.common.v1.BackMatterR\n" +
	"backMatter\"z\n" +
	"\tImportSsp\x121\n" +
	"\x04href\x18\x01 \x01(\v2\x1d.oscal.common.v1.URIReferenceR\x04href\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xb3\x03\n" +
	"\x10LocalDefinitions\x12C\n" +
	"\n" +
	"components\x18\x01 \x03(\v2#.oscal.assessment_plan.v1.ComponentR\n" +
	"components\x12P\n" +
	"\x0finventory_items\x18\x02 \x03(\v2'.oscal.assessment_plan.v1.InventoryItemR\x0einventoryItems\x124\n" +
	"\x05users\x18\x03 \x03(\v2\x1e.oscal.assessment_plan.v1.UserR\x05users\x12H\n" +
	"\n" +
	"objectives\x18\x04 \x03(\v2(.oscal.assessment_plan.v1.LocalObjectiveR\n" +
	"objectives\x12D\n" +
	"\amethods\x18\x05 \x03(\v2*.oscal.assessment_plan.v1.AssessmentMethodR\amethods\x12B\n" +
	"\n" +
	"activities\x18\x06 \x03(\v2\".oscal.assessment_plan.v1.ActivityR\n" +
	"activities\"\x9c\x02\n" +
	"\tComponent\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\x05props\x18\x05 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x06 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\a \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x93\x02\n" +
	"\rInventoryItem\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12=\n" +
	"\vdescription\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\vdescription\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xc4\x02\n" +
	"\x04User\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"short_name\x18\x03 \x01(\tR\tshortName\x12B\n" +
	"\vdescription\x18\x04 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x05 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x06 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\a \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xdb\x02\n" +
	"\x0eLocalObjective\x125\n" +
	"\n" +
	"control_id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\tcontrolId\x12B\n" +
	"\vdescription\x18\x02 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x124\n" +
	"\x05parts\x18\x05 \x03(\v2\x1e.oscal.assessment_plan.v1.PartR\x05parts\x12:\n" +
	"\aremarks\x18\x06 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xa3\x03\n" +
	"\x04Part\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\tR\x02ns\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x121\n" +
	"\x05title\x18\x05 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12/\n" +
	"\x05props\x18\x06 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\a \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x124\n" +
	"\x05parts\x18\b \x03(\v2\x1e.oscal.assessment_plan.v1.PartR\x05parts\x126\n" +
	"\x05prose\x18\t \x03(\v2 .oscal.common.v1.MarkupMultilineR\x05prose\x12:\n" +
	"\aremarks\x18\n" +
	" \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xd9\x02\n" +
	"\x10AssessmentMethod\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12B\n" +
	"\vdescription\x18\x02 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12<\n" +
	"\x04part\x18\x05 \x01(\v2(.oscal.assessment_plan.v1.AssessmentPartR\x04part\x12:\n" +
	"\aremarks\x18\x06 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xb7\x03\n" +
	"\x0eAssessmentPart\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\tR\x02ns\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x121\n" +
	"\x05title\x18\x05 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12/\n" +
	"\x05props\x18\x06 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\a \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12>\n" +
	"\x05parts\x18\b \x03(\v2(.oscal.assessment_plan.v1.AssessmentPartR\x05parts\x126\n" +
	"\x05prose\x18\t \x03(\v2 .oscal.common.v1.MarkupMultilineR\x05prose\x12:\n" +
	"\aremarks\x18\n" +
	" \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xfc\x02\n" +
	"\bActivity\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x04 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x05 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x124\n" +
	"\x05steps\x18\x06 \x03(\v2\x1e.oscal.assessment_plan.v1.StepR\x05steps\x12:\n" +
	"\aremarks\x18\a \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xc2\x02\n" +
	"\x04Step\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x04 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x05 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x06 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"=\n" +
	"\x05Terms\x124\n" +
	"\x05terms\x18\x01 \x03(\v2\x1e.oscal.assessment_plan.v1.TermR\x05terms\"\xbb\x02\n" +
	"\x04Term\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\x02id\x12/\n" +
	"\x04name\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x04name\x12@\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2 .oscal.common.v1.MarkupMultilineR\n" +
	"definition\x12/\n" +
	"\x05props\x18\x04 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x05 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x06 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x87\x01\n" +
	"\x10ReviewedControls\x12+\n" +
	"\x11control_selection\x18\x01 \x01(\tR\x10controlSelection\x12F\n" +
	"\bcontrols\x18\x02 \x03(\v2*.oscal.assessment_plan.v1.ControlSelectionR\bcontrols\"\x85\x01\n" +
	"\x10ControlSelection\x125\n" +
	"\n" +
	"control_id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\tcontrolId\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x99\x05\n" +
	"\x0eAssessmentTask\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\x05title\x18\x03 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x04 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12F\n" +
	"\bsubjects\x18\x05 \x03(\v2*.oscal.assessment_plan.v1.SubjectReferenceR\bsubjects\x124\n" +
	"\x05tasks\x18\x06 \x03(\v2\x1e.oscal.assessment_plan.v1.TaskR\x05tasks\x12a\n" +
	"\x15associated_activities\x18\a \x03(\v2,.oscal.assessment_plan.v1.AssociatedActivityR\x14associatedActivities\x12V\n" +
	"\x11responsible_roles\x18\b \x03(\v2).oscal.assessment_plan.v1.ResponsibleRoleR\x10responsibleRoles\x12/\n" +
	"\x05props\x18\t \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\v \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x99\x02\n" +
	"\x10SubjectReference\x128\n" +
	"\fsubject_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\vsubjectUuid\x121\n" +
	"\x05title\x18\x02 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\x8f\x05\n" +
	"\x04Task\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\x05title\x18\x03 \x01(\v2\x1b.oscal.common.v1.MarkupLineR\x05title\x12B\n" +
	"\vdescription\x18\x04 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12F\n" +
	"\bsubjects\x18\x05 \x03(\v2*.oscal.assessment_plan.v1.SubjectReferenceR\bsubjects\x124\n" +
	"\x05tasks\x18\x06 \x03(\v2\x1e.oscal.assessment_plan.v1.TaskR\x05tasks\x12a\n" +
	"\x15associated_activities\x18\a \x03(\v2,.oscal.assessment_plan.v1.AssociatedActivityR\x14associatedActivities\x12V\n" +
	"\x11responsible_roles\x18\b \x03(\v2).oscal.assessment_plan.v1.ResponsibleRoleR\x10responsibleRoles\x12/\n" +
	"\x05props\x18\t \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\n" +
	" \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\v \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xaf\x01\n" +
	"\x12AssociatedActivity\x12:\n" +
	"\ractivity_uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\factivityUuid\x12\x1f\n" +
	"\vinclude_all\x18\x02 \x01(\bR\n" +
	"includeAll\x12<\n" +
	"\x0eactivity_uuids\x18\x03 \x03(\v2\x15.oscal.common.v1.UUIDR\ractivityUuids\"\xe7\x01\n" +
	"\x0fResponsibleRole\x12/\n" +
	"\arole_id\x18\x01 \x01(\v2\x16.oscal.common.v1.TokenR\x06roleId\x126\n" +
	"\vparty_uuids\x18\x02 \x03(\v2\x15.oscal.common.v1.UUIDR\n" +
	"partyUuids\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12:\n" +
	"\aremarks\x18\x04 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarksBLZJgithub.com/mchorfa/xoscal/proto/oscal/assessment_plan/v1;assessment_planv1b\x06proto3"

var (
	file_assessment_plan_v1_assessment_plan_proto_rawDescOnce sync.Once
	file_assessment_plan_v1_assessment_plan_proto_rawDescData []byte
)

func file_assessment_plan_v1_assessment_plan_proto_rawDescGZIP() []byte {
	file_assessment_plan_v1_assessment_plan_proto_rawDescOnce.Do(func() {
		file_assessment_plan_v1_assessment_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assessment_plan_v1_assessment_plan_proto_rawDesc), len(file_assessment_plan_v1_assessment_plan_proto_rawDesc)))
	})
	return file_assessment_plan_v1_assessment_plan_proto_rawDescData
}

var file_assessment_plan_v1_assessment_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_assessment_plan_v1_assessment_plan_proto_goTypes = []any{
	(*AssessmentPlan)(nil),     // 0: oscal.assessment_plan.v1.AssessmentPlan
	(*ImportSsp)(nil),          // 1: oscal.assessment_plan.v1.ImportSsp
	(*LocalDefinitions)(nil),   // 2: oscal.assessment_plan.v1.LocalDefinitions
	(*Component)(nil),          // 3: oscal.assessment_plan.v1.Component
	(*InventoryItem)(nil),      // 4: oscal.assessment_plan.v1.InventoryItem
	(*User)(nil),               // 5: oscal.assessment_plan.v1.User
	(*LocalObjective)(nil),     // 6: oscal.assessment_plan.v1.LocalObjective
	(*Part)(nil),               // 7: oscal.assessment_plan.v1.Part
	(*AssessmentMethod)(nil),   // 8: oscal.assessment_plan.v1.AssessmentMethod
	(*AssessmentPart)(nil),     // 9: oscal.assessment_plan.v1.AssessmentPart
	(*Activity)(nil),           // 10: oscal.assessment_plan.v1.Activity
	(*Step)(nil),               // 11: oscal.assessment_plan.v1.Step
	(*Terms)(nil),              // 12: oscal.assessment_plan.v1.Terms
	(*Term)(nil),               // 13: oscal.assessment_plan.v1.Term
	(*ReviewedControls)(nil),   // 14: oscal.assessment_plan.v1.ReviewedControls
	(*ControlSelection)(nil),   // 15: oscal.assessment_plan.v1.ControlSelection
	(*AssessmentTask)(nil),     // 16: oscal.assessment_plan.v1.AssessmentTask
	(*SubjectReference)(nil),   // 17: oscal.assessment_plan.v1.SubjectReference
	(*Task)(nil),               // 18: oscal.assessment_plan.v1.Task
	(*AssociatedActivity)(nil), // 19: oscal.assessment_plan.v1.AssociatedActivity
	(*ResponsibleRole)(nil),    // 20: oscal.assessment_plan.v1.ResponsibleRole
	(*v1.UUID)(nil),            // 21: oscal.common.v1.UUID
	(*v1.Metadata)(nil),        // 22: oscal.common.v1.Metadata
	(*v1.BackMatter)(nil),      // 23: oscal.common.v1.BackMatter
	(*v1.URIReference)(nil),    // 24: oscal.common.v1.URIReference
	(*v1.MarkupMultiline)(nil), // 25: oscal.common.v1.MarkupMultiline
	(*v1.Property)(nil),        // 26: oscal.common.v1.Property
	(*v1.Link)(nil),            // 27: oscal.common.v1.Link
	(*v1.MarkupLine)(nil),      // 28: oscal.common.v1.MarkupLine
	(*v1.Token)(nil),           // 29: oscal.common.v1.Token
}
var file_assessment_plan_v1_assessment_plan_proto_depIdxs = []int32{
	21,  // 0: oscal.assessment_plan.v1.AssessmentPlan.uuid:type_name -> oscal.common.v1.UUID
	22,  // 1: oscal.assessment_plan.v1.AssessmentPlan.metadata:type_name -> oscal.common.v1.Metadata
	1,   // 2: oscal.assessment_plan.v1.AssessmentPlan.import_ssp:type_name -> oscal.assessment_plan.v1.ImportSsp
	2,   // 3: oscal.assessment_plan.v1.AssessmentPlan.local_definitions:type_name -> oscal.assessment_plan.v1.LocalDefinitions
	12,  // 4: oscal.assessment_plan.v1.AssessmentPlan.terms:type_name -> oscal.assessment_plan.v1.Terms
	14,  // 5: oscal.assessment_plan.v1.AssessmentPlan.reviewed_controls:type_name -> oscal.assessment_plan.v1.ReviewedControls
	16,  // 6: oscal.assessment_plan.v1.AssessmentPlan.assessment_tasks:type_name -> oscal.assessment_plan.v1.AssessmentTask
	23,  // 7: oscal.assessment_plan.v1.AssessmentPlan.back_matter:type_name -> oscal.common.v1.BackMatter
	24,  // 8: oscal.assessment_plan.v1.ImportSsp.href:type_name -> oscal.common.v1.URIReference
	25,  // 9: oscal.assessment_plan.v1.ImportSsp.remarks:type_name -> oscal.common.v1.MarkupMultiline
	3,   // 10: oscal.assessment_plan.v1.LocalDefinitions.components:type_name -> oscal.assessment_plan.v1.Component
	4,   // 11: oscal.assessment_plan.v1.LocalDefinitions.inventory_items:type_name -> oscal.assessment_plan.v1.InventoryItem
	5,   // 12: oscal.assessment_plan.v1.LocalDefinitions.users:type_name -> oscal.assessment_plan.v1.User
	6,   // 13: oscal.assessment_plan.v1.LocalDefinitions.objectives:type_name -> oscal.assessment_plan.v1.LocalObjective
	8,   // 14: oscal.assessment_plan.v1.LocalDefinitions.methods:type_name -> oscal.assessment_plan.v1.AssessmentMethod
	10,  // 15: oscal.assessment_plan.v1.LocalDefinitions.activities:type_name -> oscal.assessment_plan.v1.Activity
	21,  // 16: oscal.assessment_plan.v1.Component.uuid:type_name -> oscal.common.v1.UUID
	26,  // 17: oscal.assessment_plan.v1.Component.props:type_name -> oscal.common.v1.Property
	27,  // 18: oscal.assessment_plan.v1.Component.links:type_name -> oscal.common.v1.Link
	25,  // 19: oscal.assessment_plan.v1.Component.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 20: oscal.assessment_plan.v1.InventoryItem.uuid:type_name -> oscal.common.v1.UUID
	28,  // 21: oscal.assessment_plan.v1.InventoryItem.description:type_name -> oscal.common.v1.MarkupLine
	26,  // 22: oscal.assessment_plan.v1.InventoryItem.props:type_name -> oscal.common.v1.Property
	27,  // 23: oscal.assessment_plan.v1.InventoryItem.links:type_name -> oscal.common.v1.Link
	25,  // 24: oscal.assessment_plan.v1.InventoryItem.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 25: oscal.assessment_plan.v1.User.uuid:type_name -> oscal.common.v1.UUID
	25,  // 26: oscal.assessment_plan.v1.User.description:type_name -> oscal.common.v1.MarkupMultiline
	26,  // 27: oscal.assessment_plan.v1.User.props:type_name -> oscal.common.v1.Property
	27,  // 28: oscal.assessment_plan.v1.User.links:type_name -> oscal.common.v1.Link
	25,  // 29: oscal.assessment_plan.v1.User.remarks:type_name -> oscal.common.v1.MarkupMultiline
	29,  // 30: oscal.assessment_plan.v1.LocalObjective.control_id:type_name -> oscal.common.v1.Token
	25,  // 31: oscal.assessment_plan.v1.LocalObjective.description:type_name -> oscal.common.v1.MarkupMultiline
	26,  // 32: oscal.assessment_plan.v1.LocalObjective.props:type_name -> oscal.common.v1.Property
	27,  // 33: oscal.assessment_plan.v1.LocalObjective.links:type_name -> oscal.common.v1.Link
	7,   // 34: oscal.assessment_plan.v1.LocalObjective.parts:type_name -> oscal.assessment_plan.v1.Part
	25,  // 35: oscal.assessment_plan.v1.LocalObjective.remarks:type_name -> oscal.common.v1.MarkupMultiline
	29,  // 36: oscal.assessment_plan.v1.Part.id:type_name -> oscal.common.v1.Token
	28,  // 37: oscal.assessment_plan.v1.Part.title:type_name -> oscal.common.v1.MarkupLine
	26,  // 38: oscal.assessment_plan.v1.Part.props:type_name -> oscal.common.v1.Property
	27,  // 39: oscal.assessment_plan.v1.Part.links:type_name -> oscal.common.v1.Link
	7,   // 40: oscal.assessment_plan.v1.Part.parts:type_name -> oscal.assessment_plan.v1.Part
	25,  // 41: oscal.assessment_plan.v1.Part.prose:type_name -> oscal.common.v1.MarkupMultiline
	25,  // 42: oscal.assessment_plan.v1.Part.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 43: oscal.assessment_plan.v1.AssessmentMethod.uuid:type_name -> oscal.common.v1.UUID
	25,  // 44: oscal.assessment_plan.v1.AssessmentMethod.description:type_name -> oscal.common.v1.MarkupMultiline
	26,  // 45: oscal.assessment_plan.v1.AssessmentMethod.props:type_name -> oscal.common.v1.Property
	27,  // 46: oscal.assessment_plan.v1.AssessmentMethod.links:type_name -> oscal.common.v1.Link
	9,   // 47: oscal.assessment_plan.v1.AssessmentMethod.part:type_name -> oscal.assessment_plan.v1.AssessmentPart
	25,  // 48: oscal.assessment_plan.v1.AssessmentMethod.remarks:type_name -> oscal.common.v1.MarkupMultiline
	29,  // 49: oscal.assessment_plan.v1.AssessmentPart.id:type_name -> oscal.common.v1.Token
	28,  // 50: oscal.assessment_plan.v1.AssessmentPart.title:type_name -> oscal.common.v1.MarkupLine
	26,  // 51: oscal.assessment_plan.v1.AssessmentPart.props:type_name -> oscal.common.v1.Property
	27,  // 52: oscal.assessment_plan.v1.AssessmentPart.links:type_name -> oscal.common.v1.Link
	9,   // 53: oscal.assessment_plan.v1.AssessmentPart.parts:type_name -> oscal.assessment_plan.v1.AssessmentPart
	25,  // 54: oscal.assessment_plan.v1.AssessmentPart.prose:type_name -> oscal.common.v1.MarkupMultiline
	25,  // 55: oscal.assessment_plan.v1.AssessmentPart.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 56: oscal.assessment_plan.v1.Activity.uuid:type_name -> oscal.common.v1.UUID
	28,  // 57: oscal.assessment_plan.v1.Activity.title:type_name -> oscal.common.v1.MarkupLine
	25,  // 58: oscal.assessment_plan.v1.Activity.description:type_name -> oscal.common.v1.MarkupMultiline
	26,  // 59: oscal.assessment_plan.v1.Activity.props:type_name -> oscal.common.v1.Property
	27,  // 60: oscal.assessment_plan.v1.Activity.links:type_name -> oscal.common.v1.Link
	11,  // 61: oscal.assessment_plan.v1.Activity.steps:type_name -> oscal.assessment_plan.v1.Step
	25,  // 62: oscal.assessment_plan.v1.Activity.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 63: oscal.assessment_plan.v1.Step.uuid:type_name -> oscal.common.v1.UUID
	28,  // 64: oscal.assessment_plan.v1.Step.title:type_name -> oscal.common.v1.MarkupLine
	25,  // 65: oscal.assessment_plan.v1.Step.description:type_name -> oscal.common.v1.MarkupMultiline
	26,  // 66: oscal.assessment_plan.v1.Step.props:type_name -> oscal.common.v1.Property
	27,  // 67: oscal.assessment_plan.v1.Step.links:type_name -> oscal.common.v1.Link
	25,  // 68: oscal.assessment_plan.v1.Step.remarks:type_name -> oscal.common.v1.MarkupMultiline
	13,  // 69: oscal.assessment_plan.v1.Terms.terms:type_name -> oscal.assessment_plan.v1.Term
	29,  // 70: oscal.assessment_plan.v1.Term.id:type_name -> oscal.common.v1.Token
	28,  // 71: oscal.assessment_plan.v1.Term.name:type_name -> oscal.common.v1.MarkupLine
	25,  // 72: oscal.assessment_plan.v1.Term.definition:type_name -> oscal.common.v1.MarkupMultiline
	26,  // 73: oscal.assessment_plan.v1.Term.props:type_name -> oscal.common.v1.Property
	27,  // 74: oscal.assessment_plan.v1.Term.links:type_name -> oscal.common.v1.Link
	25,  // 75: oscal.assessment_plan.v1.Term.remarks:type_name -> oscal.common.v1.MarkupMultiline
	15,  // 76: oscal.assessment_plan.v1.ReviewedControls.controls:type_name -> oscal.assessment_plan.v1.ControlSelection
	29,  // 77: oscal.assessment_plan.v1.ControlSelection.control_id:type_name -> oscal.common.v1.Token
	25,  // 78: oscal.assessment_plan.v1.ControlSelection.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 79: oscal.assessment_plan.v1.AssessmentTask.uuid:type_name -> oscal.common.v1.UUID
	28,  // 80: oscal.assessment_plan.v1.AssessmentTask.title:type_name -> oscal.common.v1.MarkupLine
	25,  // 81: oscal.assessment_plan.v1.AssessmentTask.description:type_name -> oscal.common.v1.MarkupMultiline
	17,  // 82: oscal.assessment_plan.v1.AssessmentTask.subjects:type_name -> oscal.assessment_plan.v1.SubjectReference
	18,  // 83: oscal.assessment_plan.v1.AssessmentTask.tasks:type_name -> oscal.assessment_plan.v1.Task
	19,  // 84: oscal.assessment_plan.v1.AssessmentTask.associated_activities:type_name -> oscal.assessment_plan.v1.AssociatedActivity
	20,  // 85: oscal.assessment_plan.v1.AssessmentTask.responsible_roles:type_name -> oscal.assessment_plan.v1.ResponsibleRole
	26,  // 86: oscal.assessment_plan.v1.AssessmentTask.props:type_name -> oscal.common.v1.Property
	27,  // 87: oscal.assessment_plan.v1.AssessmentTask.links:type_name -> oscal.common.v1.Link
	25,  // 88: oscal.assessment_plan.v1.AssessmentTask.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 89: oscal.assessment_plan.v1.SubjectReference.subject_uuid:type_name -> oscal.common.v1.UUID
	28,  // 90: oscal.assessment_plan.v1.SubjectReference.title:type_name -> oscal.common.v1.MarkupLine
	26,  // 91: oscal.assessment_plan.v1.SubjectReference.props:type_name -> oscal.common.v1.Property
	27,  // 92: oscal.assessment_plan.v1.SubjectReference.links:type_name -> oscal.common.v1.Link
	25,  // 93: oscal.assessment_plan.v1.SubjectReference.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 94: oscal.assessment_plan.v1.Task.uuid:type_name -> oscal.common.v1.UUID
	28,  // 95: oscal.assessment_plan.v1.Task.title:type_name -> oscal.common.v1.MarkupLine
	25,  // 96: oscal.assessment_plan.v1.Task.description:type_name -> oscal.common.v1.MarkupMultiline
	17,  // 97: oscal.assessment_plan.v1.Task.subjects:type_name -> oscal.assessment_plan.v1.SubjectReference
	18,  // 98: oscal.assessment_plan.v1.Task.tasks:type_name -> oscal.assessment_plan.v1.Task
	19,  // 99: oscal.assessment_plan.v1.Task.associated_activities:type_name -> oscal.assessment_plan.v1.AssociatedActivity
	20,  // 100: oscal.assessment_plan.v1.Task.responsible_roles:type_name -> oscal.assessment_plan.v1.ResponsibleRole
	26,  // 101: oscal.assessment_plan.v1.Task.props:type_name -> oscal.common.v1.Property
	27,  // 102: oscal.assessment_plan.v1.Task.links:type_name -> oscal.common.v1.Link
	25,  // 103: oscal.assessment_plan.v1.Task.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21,  // 104: oscal.assessment_plan.v1.AssociatedActivity.activity_uuid:type_name -> oscal.common.v1.UUID
	21,  // 105: oscal.assessment_plan.v1.AssociatedActivity.activity_uuids:type_name -> oscal.common.v1.UUID
	29,  // 106: oscal.assessment_plan.v1.ResponsibleRole.role_id:type_name -> oscal.common.v1.Token
	21,  // 107: oscal.assessment_plan.v1.ResponsibleRole.party_uuids:type_name -> oscal.common.v1.UUID
	26,  // 108: oscal.assessment_plan.v1.ResponsibleRole.props:type_name -> oscal.common.v1.Property
	25,  // 109: oscal.assessment_plan.v1.ResponsibleRole.remarks:type_name -> oscal.common.v1.MarkupMultiline
	110, // [110:110] is the sub-list for method output_type
	110, // [110:110] is the sub-list for method input_type
	110, // [110:110] is the sub-list for extension type_name
	110, // [110:110] is the sub-list for extension extendee
	0,   // [0:110] is the sub-list for field type_name
}

func init() { file_assessment_plan_v1_assessment_plan_proto_init() }
func file_assessment_plan_v1_assessment_plan_proto_init() {
	if File_assessment_plan_v1_assessment_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assessment_plan_v1_assessment_plan_proto_rawDesc), len(file_assessment_plan_v1_assessment_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assessment_plan_v1_assessment_plan_proto_goTypes,
		DependencyIndexes: file_assessment_plan_v1_assessment_plan_proto_depIdxs,
		MessageInfos:      file_assessment_plan_v1_assessment_plan_proto_msgTypes,
	}.Build()
	File_assessment_plan_v1_assessment_plan_proto = out.File
	file_assessment_plan_v1_assessment_plan_proto_goTypes = nil
	file_assessment_plan_v1_assessment_plan_proto_depIdxs = nil
}
