// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mapping/v1/mapping.proto

package mappingv1

import (
	v1 "github.com/mchorfa/xoscal/proto/oscal/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MappingCollection is the OSCAL 1.2 mapping-collection document root.
// Fields 3-15 predate the released Mapping model and are retained only for
// wire compatibility; new code uses provenance, mappings, and back_matter.
type MappingCollection struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Uuid     *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Metadata *v1.Metadata           `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	MatchingRationale string `protobuf:"bytes,3,opt,name=matching_rationale,json=matchingRationale,proto3" json:"matching_rationale,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	SourceResource *MappingResourceReference `protobuf:"bytes,5,opt,name=source_resource,json=sourceResource,proto3" json:"source_resource,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	TargetResource *MappingResourceReference `protobuf:"bytes,6,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Maps []*Map `protobuf:"bytes,7,rep,name=maps,proto3" json:"maps,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Props []*v1.Property `protobuf:"bytes,8,rep,name=props,proto3" json:"props,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Links []*v1.Link `protobuf:"bytes,9,rep,name=links,proto3" json:"links,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Remarks []*v1.MarkupMultiline `protobuf:"bytes,10,rep,name=remarks,proto3" json:"remarks,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	MappingDescription *MappingDescription `protobuf:"bytes,11,opt,name=mapping_description,json=mappingDescription,proto3" json:"mapping_description,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	SourceGapSummary *GapSummary `protobuf:"bytes,12,opt,name=source_gap_summary,json=sourceGapSummary,proto3" json:"source_gap_summary,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	TargetGapSummary *GapSummary `protobuf:"bytes,13,opt,name=target_gap_summary,json=targetGapSummary,proto3" json:"target_gap_summary,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	ConfidenceScore *ConfidenceScore `protobuf:"bytes,14,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Coverage      *Coverage          `protobuf:"bytes,15,opt,name=coverage,proto3" json:"coverage,omitempty"`
	Provenance    *MappingProvenance `protobuf:"bytes,16,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Mappings      []*ControlMapping  `protobuf:"bytes,17,rep,name=mappings,proto3" json:"mappings,omitempty"`
	BackMatter    *v1.BackMatter     `protobuf:"bytes,18,opt,name=back_matter,json=backMatter,proto3" json:"back_matter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingCollection) Reset() {
	*x = MappingCollection{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingCollection) ProtoMessage() {}

func (x *MappingCollection) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingCollection.ProtoReflect.Descriptor instead.
func (*MappingCollection) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{0}
}

func (x *MappingCollection) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *MappingCollection) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetMatchingRationale() string {
	if x != nil {
		return x.MatchingRationale
	}
	return ""
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetSourceResource() *MappingResourceReference {
	if x != nil {
		return x.SourceResource
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetTargetResource() *MappingResourceReference {
	if x != nil {
		return x.TargetResource
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetMaps() []*Map {
	if x != nil {
		return x.Maps
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetMappingDescription() *MappingDescription {
	if x != nil {
		return x.MappingDescription
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetSourceGapSummary() *GapSummary {
	if x != nil {
		return x.SourceGapSummary
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetTargetGapSummary() *GapSummary {
	if x != nil {
		return x.TargetGapSummary
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetConfidenceScore() *ConfidenceScore {
	if x != nil {
		return x.ConfidenceScore
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *MappingCollection) GetCoverage() *Coverage {
	if x != nil {
		return x.Coverage
	}
	return nil
}

func (x *MappingCollection) GetProvenance() *MappingProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *MappingCollection) GetMappings() []*ControlMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *MappingCollection) GetBackMatter() *v1.BackMatter {
	if x != nil {
		return x.BackMatter
	}
	return nil
}

// ControlMapping represents one source-resource to target-resource mapping.
type ControlMapping struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Uuid               *v1.UUID                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Method             string                    `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	MatchingRationale  string                    `protobuf:"bytes,3,opt,name=matching_rationale,json=matchingRationale,proto3" json:"matching_rationale,omitempty"`
	Status             string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	SourceResource     *MappingResourceReference `protobuf:"bytes,5,opt,name=source_resource,json=sourceResource,proto3" json:"source_resource,omitempty"`
	TargetResource     *MappingResourceReference `protobuf:"bytes,6,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	Maps               []*Map                    `protobuf:"bytes,7,rep,name=maps,proto3" json:"maps,omitempty"`
	Props              []*v1.Property            `protobuf:"bytes,8,rep,name=props,proto3" json:"props,omitempty"`
	Links              []*v1.Link                `protobuf:"bytes,9,rep,name=links,proto3" json:"links,omitempty"`
	Remarks            []*v1.MarkupMultiline     `protobuf:"bytes,10,rep,name=remarks,proto3" json:"remarks,omitempty"`
	MappingDescription *v1.MarkupMultiline       `protobuf:"bytes,11,opt,name=mapping_description,json=mappingDescription,proto3" json:"mapping_description,omitempty"`
	SourceGapSummary   *GapSummary               `protobuf:"bytes,12,opt,name=source_gap_summary,json=sourceGapSummary,proto3" json:"source_gap_summary,omitempty"`
	TargetGapSummary   *GapSummary               `protobuf:"bytes,13,opt,name=target_gap_summary,json=targetGapSummary,proto3" json:"target_gap_summary,omitempty"`
	ConfidenceScore    *ConfidenceScore          `protobuf:"bytes,14,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Coverage           *Coverage                 `protobuf:"bytes,15,opt,name=coverage,proto3" json:"coverage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ControlMapping) Reset() {
	*x = ControlMapping{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMapping) ProtoMessage() {}

func (x *ControlMapping) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMapping.ProtoReflect.Descriptor instead.
func (*ControlMapping) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMapping) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ControlMapping) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ControlMapping) GetMatchingRationale() string {
	if x != nil {
		return x.MatchingRationale
	}
	return ""
}

func (x *ControlMapping) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ControlMapping) GetSourceResource() *MappingResourceReference {
	if x != nil {
		return x.SourceResource
	}
	return nil
}

func (x *ControlMapping) GetTargetResource() *MappingResourceReference {
	if x != nil {
		return x.TargetResource
	}
	return nil
}

func (x *ControlMapping) GetMaps() []*Map {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *ControlMapping) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *ControlMapping) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ControlMapping) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *ControlMapping) GetMappingDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.MappingDescription
	}
	return nil
}

func (x *ControlMapping) GetSourceGapSummary() *GapSummary {
	if x != nil {
		return x.SourceGapSummary
	}
	return nil
}

func (x *ControlMapping) GetTargetGapSummary() *GapSummary {
	if x != nil {
		return x.TargetGapSummary
	}
	return nil
}

func (x *ControlMapping) GetConfidenceScore() *ConfidenceScore {
	if x != nil {
		return x.ConfidenceScore
	}
	return nil
}

func (x *ControlMapping) GetCoverage() *Coverage {
	if x != nil {
		return x.Coverage
	}
	return nil
}

// MappingResourceReference represents a mapped resource reference
type MappingResourceReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ns            string                 `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Href          *v1.URIReference       `protobuf:"bytes,3,opt,name=href,proto3" json:"href,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,6,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingResourceReference) Reset() {
	*x = MappingResourceReference{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingResourceReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingResourceReference) ProtoMessage() {}

func (x *MappingResourceReference) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingResourceReference.ProtoReflect.Descriptor instead.
func (*MappingResourceReference) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{2}
}

func (x *MappingResourceReference) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *MappingResourceReference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MappingResourceReference) GetHref() *v1.URIReference {
	if x != nil {
		return x.Href
	}
	return nil
}

func (x *MappingResourceReference) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *MappingResourceReference) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MappingResourceReference) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// Map represents a mapping entry
type Map struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uuid              *v1.UUID               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ns                string                 `protobuf:"bytes,2,opt,name=ns,proto3" json:"ns,omitempty"`
	MatchingRationale string                 `protobuf:"bytes,3,opt,name=matching_rationale,json=matchingRationale,proto3" json:"matching_rationale,omitempty"`
	Relationship      *v1.Token              `protobuf:"bytes,4,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Sources           []*MappingItem         `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	Targets           []*MappingItem         `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	Qualifiers        []*QualifierItem       `protobuf:"bytes,7,rep,name=qualifiers,proto3" json:"qualifiers,omitempty"`
	ConfidenceScore   *ConfidenceScore       `protobuf:"bytes,8,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Coverage          *Coverage              `protobuf:"bytes,9,opt,name=coverage,proto3" json:"coverage,omitempty"`
	Props             []*v1.Property         `protobuf:"bytes,10,rep,name=props,proto3" json:"props,omitempty"`
	Links             []*v1.Link             `protobuf:"bytes,11,rep,name=links,proto3" json:"links,omitempty"`
	Remarks           []*v1.MarkupMultiline  `protobuf:"bytes,12,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Map) Reset() {
	*x = Map{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{3}
}

func (x *Map) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Map) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Map) GetMatchingRationale() string {
	if x != nil {
		return x.MatchingRationale
	}
	return ""
}

func (x *Map) GetRelationship() *v1.Token {
	if x != nil {
		return x.Relationship
	}
	return nil
}

func (x *Map) GetSources() []*MappingItem {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Map) GetTargets() []*MappingItem {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Map) GetQualifiers() []*QualifierItem {
	if x != nil {
		return x.Qualifiers
	}
	return nil
}

func (x *Map) GetConfidenceScore() *ConfidenceScore {
	if x != nil {
		return x.ConfidenceScore
	}
	return nil
}

func (x *Map) GetCoverage() *Coverage {
	if x != nil {
		return x.Coverage
	}
	return nil
}

func (x *Map) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Map) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Map) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// MappingItem represents a mapping entry item (source or target)
type MappingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	IdRef         string                 `protobuf:"bytes,2,opt,name=id_ref,json=idRef,proto3" json:"id_ref,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingItem) Reset() {
	*x = MappingItem{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingItem) ProtoMessage() {}

func (x *MappingItem) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingItem.ProtoReflect.Descriptor instead.
func (*MappingItem) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{4}
}

func (x *MappingItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MappingItem) GetIdRef() string {
	if x != nil {
		return x.IdRef
	}
	return ""
}

func (x *MappingItem) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *MappingItem) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MappingItem) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// QualifierItem represents an OSCAL relationship qualifier. Fields 1-4 are
// retained for wire compatibility with the pre-release mapping prototype.
type QualifierItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	IdRef string `protobuf:"bytes,2,opt,name=id_ref,json=idRef,proto3" json:"id_ref,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Props []*v1.Property `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Links         []*v1.Link            `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	Subject       string                `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate     string                `protobuf:"bytes,7,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Category      string                `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Description   *v1.MarkupMultiline   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualifierItem) Reset() {
	*x = QualifierItem{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifierItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifierItem) ProtoMessage() {}

func (x *QualifierItem) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifierItem.ProtoReflect.Descriptor instead.
func (*QualifierItem) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{5}
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *QualifierItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *QualifierItem) GetIdRef() string {
	if x != nil {
		return x.IdRef
	}
	return ""
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *QualifierItem) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *QualifierItem) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *QualifierItem) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *QualifierItem) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *QualifierItem) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *QualifierItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QualifierItem) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

// ConfidenceScore is either a category or a percentage from 0 through 1.
// Fields 1-5 are retained for wire compatibility with the prototype model.
type ConfidenceScore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Props []*v1.Property `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Links []*v1.Link `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Remarks       []*v1.MarkupMultiline `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	Category      string                `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Percentage    *v1.Decimal           `protobuf:"bytes,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfidenceScore) Reset() {
	*x = ConfidenceScore{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceScore) ProtoMessage() {}

func (x *ConfidenceScore) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceScore.ProtoReflect.Descriptor instead.
func (*ConfidenceScore) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{6}
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *ConfidenceScore) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *ConfidenceScore) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *ConfidenceScore) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *ConfidenceScore) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *ConfidenceScore) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *ConfidenceScore) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ConfidenceScore) GetPercentage() *v1.Decimal {
	if x != nil {
		return x.Percentage
	}
	return nil
}

// Coverage records target coverage and the method used to derive it.
// Fields 1-5 are retained for wire compatibility with the prototype model.
type Coverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Props []*v1.Property `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Links []*v1.Link `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Remarks          []*v1.MarkupMultiline `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	GenerationMethod string                `protobuf:"bytes,6,opt,name=generation_method,json=generationMethod,proto3" json:"generation_method,omitempty"`
	TargetCoverage   *v1.Decimal           `protobuf:"bytes,7,opt,name=target_coverage,json=targetCoverage,proto3" json:"target_coverage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Coverage) Reset() {
	*x = Coverage{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coverage) ProtoMessage() {}

func (x *Coverage) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coverage.ProtoReflect.Descriptor instead.
func (*Coverage) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{7}
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *Coverage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *Coverage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *Coverage) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *Coverage) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *Coverage) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *Coverage) GetGenerationMethod() string {
	if x != nil {
		return x.GenerationMethod
	}
	return ""
}

func (x *Coverage) GetTargetCoverage() *v1.Decimal {
	if x != nil {
		return x.TargetCoverage
	}
	return nil
}

// GapSummary selects controls that are not mapped.
// Fields 1-5 are retained for wire compatibility with the prototype model.
type GapSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Gaps []string `protobuf:"bytes,2,rep,name=gaps,proto3" json:"gaps,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Props []*v1.Property `protobuf:"bytes,3,rep,name=props,proto3" json:"props,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Links []*v1.Link `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
	Remarks          []*v1.MarkupMultiline `protobuf:"bytes,5,rep,name=remarks,proto3" json:"remarks,omitempty"`
	Uuid             *v1.UUID              `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UnmappedControls []*SelectControlById  `protobuf:"bytes,7,rep,name=unmapped_controls,json=unmappedControls,proto3" json:"unmapped_controls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GapSummary) Reset() {
	*x = GapSummary{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GapSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GapSummary) ProtoMessage() {}

func (x *GapSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GapSummary.ProtoReflect.Descriptor instead.
func (*GapSummary) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{8}
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *GapSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *GapSummary) GetGaps() []string {
	if x != nil {
		return x.Gaps
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *GapSummary) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *GapSummary) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Deprecated: Marked as deprecated in mapping/v1/mapping.proto.
func (x *GapSummary) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *GapSummary) GetUuid() *v1.UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *GapSummary) GetUnmappedControls() []*SelectControlById {
	if x != nil {
		return x.UnmappedControls
	}
	return nil
}

// MappingDescription is the deprecated prototype wrapper. Released OSCAL uses
// MarkupMultiline directly for mapping-description.
type MappingDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   *v1.MarkupMultiline    `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Props         []*v1.Property         `protobuf:"bytes,2,rep,name=props,proto3" json:"props,omitempty"`
	Links         []*v1.Link             `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,4,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingDescription) Reset() {
	*x = MappingDescription{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingDescription) ProtoMessage() {}

func (x *MappingDescription) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingDescription.ProtoReflect.Descriptor instead.
func (*MappingDescription) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{9}
}

func (x *MappingDescription) GetDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *MappingDescription) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *MappingDescription) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MappingDescription) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// MappingProvenance records how the collection was produced and its status.
type MappingProvenance struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Method             string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	MatchingRationale  string                 `protobuf:"bytes,2,opt,name=matching_rationale,json=matchingRationale,proto3" json:"matching_rationale,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ConfidenceScore    *ConfidenceScore       `protobuf:"bytes,4,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Coverage           *Coverage              `protobuf:"bytes,5,opt,name=coverage,proto3" json:"coverage,omitempty"`
	MappingDescription *v1.MarkupMultiline    `protobuf:"bytes,6,opt,name=mapping_description,json=mappingDescription,proto3" json:"mapping_description,omitempty"`
	ResponsibleParties []*v1.ResponsibleParty `protobuf:"bytes,7,rep,name=responsible_parties,json=responsibleParties,proto3" json:"responsible_parties,omitempty"`
	Props              []*v1.Property         `protobuf:"bytes,8,rep,name=props,proto3" json:"props,omitempty"`
	Links              []*v1.Link             `protobuf:"bytes,9,rep,name=links,proto3" json:"links,omitempty"`
	Remarks            []*v1.MarkupMultiline  `protobuf:"bytes,10,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MappingProvenance) Reset() {
	*x = MappingProvenance{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingProvenance) ProtoMessage() {}

func (x *MappingProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingProvenance.ProtoReflect.Descriptor instead.
func (*MappingProvenance) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{10}
}

func (x *MappingProvenance) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MappingProvenance) GetMatchingRationale() string {
	if x != nil {
		return x.MatchingRationale
	}
	return ""
}

func (x *MappingProvenance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MappingProvenance) GetConfidenceScore() *ConfidenceScore {
	if x != nil {
		return x.ConfidenceScore
	}
	return nil
}

func (x *MappingProvenance) GetCoverage() *Coverage {
	if x != nil {
		return x.Coverage
	}
	return nil
}

func (x *MappingProvenance) GetMappingDescription() *v1.MarkupMultiline {
	if x != nil {
		return x.MappingDescription
	}
	return nil
}

func (x *MappingProvenance) GetResponsibleParties() []*v1.ResponsibleParty {
	if x != nil {
		return x.ResponsibleParties
	}
	return nil
}

func (x *MappingProvenance) GetProps() []*v1.Property {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *MappingProvenance) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MappingProvenance) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

// SelectControlById selects explicit or pattern-matched controls.
type SelectControlById struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WithChildControls string                 `protobuf:"bytes,1,opt,name=with_child_controls,json=withChildControls,proto3" json:"with_child_controls,omitempty"`
	WithIds           []*v1.Token            `protobuf:"bytes,2,rep,name=with_ids,json=withIds,proto3" json:"with_ids,omitempty"`
	Matching          []*Matching            `protobuf:"bytes,3,rep,name=matching,proto3" json:"matching,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SelectControlById) Reset() {
	*x = SelectControlById{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectControlById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectControlById) ProtoMessage() {}

func (x *SelectControlById) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectControlById.ProtoReflect.Descriptor instead.
func (*SelectControlById) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{11}
}

func (x *SelectControlById) GetWithChildControls() string {
	if x != nil {
		return x.WithChildControls
	}
	return ""
}

func (x *SelectControlById) GetWithIds() []*v1.Token {
	if x != nil {
		return x.WithIds
	}
	return nil
}

func (x *SelectControlById) GetMatching() []*Matching {
	if x != nil {
		return x.Matching
	}
	return nil
}

// Matching selects controls by a glob expression.
type Matching struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Remarks       []*v1.MarkupMultiline  `protobuf:"bytes,2,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matching) Reset() {
	*x = Matching{}
	mi := &file_mapping_v1_mapping_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matching) ProtoMessage() {}

func (x *Matching) ProtoReflect() protoreflect.Message {
	mi := &file_mapping_v1_mapping_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matching.ProtoReflect.Descriptor instead.
func (*Matching) Descriptor() ([]byte, []int) {
	return file_mapping_v1_mapping_proto_rawDescGZIP(), []int{12}
}

func (x *Matching) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Matching) GetRemarks() []*v1.MarkupMultiline {
	if x != nil {
		return x.Remarks
	}
	return nil
}

var File_mapping_v1_mapping_proto protoreflect.FileDescriptor

const file_mapping_v1_mapping_proto_rawDesc = "" +
	"\n" +
	"\x18mapping/v1/mapping.proto\x12\x10oscal.mapping.v1\x1a\x16common/v1/common.proto\"\x95\t\n" +
	"\x11MappingCollection\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.oscal.common.v1.MetadataR\bmetadata\x121\n" +
	"\x12matching_rationale\x18\x03 \x01(\tB\x02\x18\x01R\x11matchingRationale\x12\x1a\n" +
	"\x06status\x18\x04 \x01(\tB\x02\x18\x01R\x06status\x12W\n" +
	"\x0fsource_resource\x18\x05 \x01(\v2*.oscal.mapping.v1.MappingResourceReferenceB\x02\x18\x01R\x0esourceResource\x12W\n" +
	"\x0ftarget_resource\x18\x06 \x01(\v2*.oscal.mapping.v1.MappingResourceReferenceB\x02\x18\x01R\x0etargetResource\x12-\n" +
	"\x04maps\x18\a \x03(\v2\x15.oscal.mapping.v1.MapB\x02\x18\x01R\x04maps\x123\n" +
	"\x05props\x18\b \x03(\v2\x19.oscal.common.v1.PropertyB\x02\x18\x01R\x05props\x12/\n" +
	"\x05links\x18\t \x03(\v2\x15.oscal.common.v1.LinkB\x02\x18\x01R\x05links\x12>\n" +
	"\aremarks\x18\n" +
	" \x03(\v2 .oscal.common.v1.MarkupMultilineB\x02\x18\x01R\aremarks\x12Y\n" +
	"\x13mapping_description\x18\v \x01(\v2$.oscal.mapping.v1.MappingDescriptionB\x02\x18\x01R\x12mappingDescription\x12N\n" +
	"\x12source_gap_summary\x18\f \x01(\v2\x1c.oscal.mapping.v1.GapSummaryB\x02\x18\x01R\x10sourceGapSummary\x12N\n" +
	"\x12target_gap_summary\x18\r \x01(\v2\x1c.oscal.mapping.v1.GapSummaryB\x02\x18\x01R\x10targetGapSummary\x12P\n" +
	"\x10confidence_score\x18\x0e \x01(\v2!.oscal.mapping.v1.ConfidenceScoreB\x02\x18\x01R\x0fconfidenceScore\x12:\n" +
	"\bcoverage\x18\x0f \x01(\v2\x1a.oscal.mapping.v1.CoverageB\x02\x18\x01R\bcoverage\x12C\n" +
	"\n" +
	"provenance\x18\x10 \x01(\v2#.oscal.mapping.v1.MappingProvenanceR\n" +
	"provenance\x12<\n" +
	"\bmappings\x18\x11 \x03(\v2 .oscal.mapping.v1.ControlMappingR\bmappings\x12<\n" +
	"\vback_matter\x18\x12 \x01(\v2\x1b.oscal.common.v1.BackMatterR\n" +
	"backMatter\"\xfa\x06\n" +
	"\x0eControlMapping\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12-\n" +
	"\x12matching_rationale\x18\x03 \x01(\tR\x11matchingRationale\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12S\n" +
	"\x0fsource_resource\x18\x05 \x01(\v2*.oscal.mapping.v1.MappingResourceReferenceR\x0esourceResource\x12S\n" +
	"\x0ftarget_resource\x18\x06 \x01(\v2*.oscal.mapping.v1.MappingResourceReferenceR\x0etargetResource\x12)\n" +
	"\x04maps\x18\a \x03(\v2\x15.oscal.mapping.v1.MapR\x04maps\x12/\n" +
	"\x05props\x18\b \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\t \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\n" +
	" \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\x12Q\n" +
	"\x13mapping_description\x18\v \x01(\v2 .oscal.common.v1.MarkupMultilineR\x12mappingDescription\x12J\n" +
	"\x12source_gap_summary\x18\f \x01(\v2\x1c.oscal.mapping.v1.GapSummaryR\x10sourceGapSummary\x12J\n" +
	"\x12target_gap_summary\x18\r \x01(\v2\x1c.oscal.mapping.v1.GapSummaryR\x10targetGapSummary\x12L\n" +
	"\x10confidence_score\x18\x0e \x01(\v2!.oscal.mapping.v1.ConfidenceScoreR\x0fconfidenceScore\x126\n" +
	"\bcoverage\x18\x0f \x01(\v2\x1a.oscal.mapping.v1.CoverageR\bcoverage\"\x8b\x02\n" +
	"\x18MappingResourceReference\x12\x0e\n" +
	"\x02ns\x18\x01 \x01(\tR\x02ns\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\x04href\x18\x03 \x01(\v2\x1d.oscal.common.v1.URIReferenceR\x04href\x12/\n" +
	"\x05props\x18\x04 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x05 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x06 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xfe\x04\n" +
	"\x03Map\x12)\n" +
	"\x04uuid\x18\x01 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12\x0e\n" +
	"\x02ns\x18\x02 \x01(\tR\x02ns\x12-\n" +
	"\x12matching_rationale\x18\x03 \x01(\tR\x11matchingRationale\x12:\n" +
	"\frelationship\x18\x04 \x01(\v2\x16.oscal.common.v1.TokenR\frelationship\x127\n" +
	"\asources\x18\x05 \x03(\v2\x1d.oscal.mapping.v1.MappingItemR\asources\x127\n" +
	"\atargets\x18\x06 \x03(\v2\x1d.oscal.mapping.v1.MappingItemR\atargets\x12?\n" +
	"\n" +
	"qualifiers\x18\a \x03(\v2\x1f.oscal.mapping.v1.QualifierItemR\n" +
	"qualifiers\x12L\n" +
	"\x10confidence_score\x18\b \x01(\v2!.oscal.mapping.v1.ConfidenceScoreR\x0fconfidenceScore\x126\n" +
	"\bcoverage\x18\t \x01(\v2\x1a.oscal.mapping.v1.CoverageR\bcoverage\x12/\n" +
	"\x05props\x18\n" +
	" \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\v \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\f \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xd2\x01\n" +
	"\vMappingItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x15\n" +
	"\x06id_ref\x18\x02 \x01(\tR\x05idRef\x12/\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xfc\x02\n" +
	"\rQualifierItem\x12\x16\n" +
	"\x04type\x18\x01 \x01(\tB\x02\x18\x01R\x04type\x12\x19\n" +
	"\x06id_ref\x18\x02 \x01(\tB\x02\x18\x01R\x05idRef\x123\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyB\x02\x18\x01R\x05props\x12/\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkB\x02\x18\x01R\x05links\x12:\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x1c\n" +
	"\tpredicate\x18\a \x01(\tR\tpredicate\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12B\n" +
	"\vdescription\x18\t \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\"\xc3\x02\n" +
	"\x0fConfidenceScore\x12\x18\n" +
	"\x05value\x18\x01 \x01(\x01B\x02\x18\x01R\x05value\x12\x1a\n" +
	"\x06method\x18\x02 \x01(\tB\x02\x18\x01R\x06method\x123\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyB\x02\x18\x01R\x05props\x12/\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkB\x02\x18\x01R\x05links\x12>\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineB\x02\x18\x01R\aremarks\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x128\n" +
	"\n" +
	"percentage\x18\a \x01(\v2\x18.oscal.common.v1.DecimalR\n" +
	"percentage\"\xd6\x02\n" +
	"\bCoverage\x12\x18\n" +
	"\x05value\x18\x01 \x01(\x01B\x02\x18\x01R\x05value\x12\x1a\n" +
	"\x06method\x18\x02 \x01(\tB\x02\x18\x01R\x06method\x123\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyB\x02\x18\x01R\x05props\x12/\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkB\x02\x18\x01R\x05links\x12>\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineB\x02\x18\x01R\aremarks\x12+\n" +
	"\x11generation_method\x18\x06 \x01(\tR\x10generationMethod\x12A\n" +
	"\x0ftarget_coverage\x18\a \x01(\v2\x18.oscal.common.v1.DecimalR\x0etargetCoverage\"\xe1\x02\n" +
	"\n" +
	"GapSummary\x12\x18\n" +
	"\x05count\x18\x01 \x01(\x05B\x02\x18\x01R\x05count\x12\x16\n" +
	"\x04gaps\x18\x02 \x03(\tB\x02\x18\x01R\x04gaps\x123\n" +
	"\x05props\x18\x03 \x03(\v2\x19.oscal.common.v1.PropertyB\x02\x18\x01R\x05props\x12/\n" +
	"\x05links\x18\x04 \x03(\v2\x15.oscal.common.v1.LinkB\x02\x18\x01R\x05links\x12>\n" +
	"\aremarks\x18\x05 \x03(\v2 .oscal.common.v1.MarkupMultilineB\x02\x18\x01R\aremarks\x12)\n" +
	"\x04uuid\x18\x06 \x01(\v2\x15.oscal.common.v1.UUIDR\x04uuid\x12P\n" +
	"\x11unmapped_controls\x18\a \x03(\v2#.oscal.mapping.v1.SelectControlByIdR\x10unmappedControls\"\xf2\x01\n" +
	"\x12MappingDescription\x12B\n" +
	"\vdescription\x18\x01 \x01(\v2 .oscal.common.v1.MarkupMultilineR\vdescription\x12/\n" +
	"\x05props\x18\x02 \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\x03 \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\x04 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xb9\x04\n" +
	"\x11MappingProvenance\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12-\n" +
	"\x12matching_rationale\x18\x02 \x01(\tR\x11matchingRationale\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12L\n" +
	"\x10confidence_score\x18\x04 \x01(\v2!.oscal.mapping.v1.ConfidenceScoreR\x0fconfidenceScore\x126\n" +
	"\bcoverage\x18\x05 \x01(\v2\x1a.oscal.mapping.v1.CoverageR\bcoverage\x12Q\n" +
	"\x13mapping_description\x18\x06 \x01(\v2 .oscal.common.v1.MarkupMultilineR\x12mappingDescription\x12R\n" +
	"\x13responsible_parties\x18\a \x03(\v2!.oscal.common.v1.ResponsiblePartyR\x12responsibleParties\x12/\n" +
	"\x05props\x18\b \x03(\v2\x19.oscal.common.v1.PropertyR\x05props\x12+\n" +
	"\x05links\x18\t \x03(\v2\x15.oscal.common.v1.LinkR\x05links\x12:\n" +
	"\aremarks\x18\n" +
	" \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarks\"\xae\x01\n" +
	"\x11SelectControlById\x12.\n" +
	"\x13with_child_controls\x18\x01 \x01(\tR\x11withChildControls\x121\n" +
	"\bwith_ids\x18\x02 \x03(\v2\x16.oscal.common.v1.TokenR\awithIds\x126\n" +
	"\bmatching\x18\x03 \x03(\v2\x1a.oscal.mapping.v1.MatchingR\bmatching\"`\n" +
	"\bMatching\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12:\n" +
	"\aremarks\x18\x02 \x03(\v2 .oscal.common.v1.MarkupMultilineR\aremarksB<Z:github.com/mchorfa/xoscal/proto/oscal/mapping/v1;mappingv1b\x06proto3"

var (
	file_mapping_v1_mapping_proto_rawDescOnce sync.Once
	file_mapping_v1_mapping_proto_rawDescData []byte
)

func file_mapping_v1_mapping_proto_rawDescGZIP() []byte {
	file_mapping_v1_mapping_proto_rawDescOnce.Do(func() {
		file_mapping_v1_mapping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapping_v1_mapping_proto_rawDesc), len(file_mapping_v1_mapping_proto_rawDesc)))
	})
	return file_mapping_v1_mapping_proto_rawDescData
}

var file_mapping_v1_mapping_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_mapping_v1_mapping_proto_goTypes = []any{
	(*MappingCollection)(nil),        // 0: oscal.mapping.v1.MappingCollection
	(*ControlMapping)(nil),           // 1: oscal.mapping.v1.ControlMapping
	(*MappingResourceReference)(nil), // 2: oscal.mapping.v1.MappingResourceReference
	(*Map)(nil),                      // 3: oscal.mapping.v1.Map
	(*MappingItem)(nil),              // 4: oscal.mapping.v1.MappingItem
	(*QualifierItem)(nil),            // 5: oscal.mapping.v1.QualifierItem
	(*ConfidenceScore)(nil),          // 6: oscal.mapping.v1.ConfidenceScore
	(*Coverage)(nil),                 // 7: oscal.mapping.v1.Coverage
	(*GapSummary)(nil),               // 8: oscal.mapping.v1.GapSummary
	(*MappingDescription)(nil),       // 9: oscal.mapping.v1.MappingDescription
	(*MappingProvenance)(nil),        // 10: oscal.mapping.v1.MappingProvenance
	(*SelectControlById)(nil),        // 11: oscal.mapping.v1.SelectControlById
	(*Matching)(nil),                 // 12: oscal.mapping.v1.Matching
	(*v1.UUID)(nil),                  // 13: oscal.common.v1.UUID
	(*v1.Metadata)(nil),              // 14: oscal.common.v1.Metadata
	(*v1.Property)(nil),              // 15: oscal.common.v1.Property
	(*v1.Link)(nil),                  // 16: oscal.common.v1.Link
	(*v1.MarkupMultiline)(nil),       // 17: oscal.common.v1.MarkupMultiline
	(*v1.BackMatter)(nil),            // 18: oscal.common.v1.BackMatter
	(*v1.URIReference)(nil),          // 19: oscal.common.v1.URIReference
	(*v1.Token)(nil),                 // 20: oscal.common.v1.Token
	(*v1.Decimal)(nil),               // 21: oscal.common.v1.Decimal
	(*v1.ResponsibleParty)(nil),      // 22: oscal.common.v1.ResponsibleParty
}
var file_mapping_v1_mapping_proto_depIdxs = []int32{
	13, // 0: oscal.mapping.v1.MappingCollection.uuid:type_name -> oscal.common.v1.UUID
	14, // 1: oscal.mapping.v1.MappingCollection.metadata:type_name -> oscal.common.v1.Metadata
	2,  // 2: oscal.mapping.v1.MappingCollection.source_resource:type_name -> oscal.mapping.v1.MappingResourceReference
	2,  // 3: oscal.mapping.v1.MappingCollection.target_resource:type_name -> oscal.mapping.v1.MappingResourceReference
	3,  // 4: oscal.mapping.v1.MappingCollection.maps:type_name -> oscal.mapping.v1.Map
	15, // 5: oscal.mapping.v1.MappingCollection.props:type_name -> oscal.common.v1.Property
	16, // 6: oscal.mapping.v1.MappingCollection.links:type_name -> oscal.common.v1.Link
	17, // 7: oscal.mapping.v1.MappingCollection.remarks:type_name -> oscal.common.v1.MarkupMultiline
	9,  // 8: oscal.mapping.v1.MappingCollection.mapping_description:type_name -> oscal.mapping.v1.MappingDescription
	8,  // 9: oscal.mapping.v1.MappingCollection.source_gap_summary:type_name -> oscal.mapping.v1.GapSummary
	8,  // 10: oscal.mapping.v1.MappingCollection.target_gap_summary:type_name -> oscal.mapping.v1.GapSummary
	6,  // 11: oscal.mapping.v1.MappingCollection.confidence_score:type_name -> oscal.mapping.v1.ConfidenceScore
	7,  // 12: oscal.mapping.v1.MappingCollection.coverage:type_name -> oscal.mapping.v1.Coverage
	10, // 13: oscal.mapping.v1.MappingCollection.provenance:type_name -> oscal.mapping.v1.MappingProvenance
	1,  // 14: oscal.mapping.v1.MappingCollection.mappings:type_name -> oscal.mapping.v1.ControlMapping
	18, // 15: oscal.mapping.v1.MappingCollection.back_matter:type_name -> oscal.common.v1.BackMatter
	13, // 16: oscal.mapping.v1.ControlMapping.uuid:type_name -> oscal.common.v1.UUID
	2,  // 17: oscal.mapping.v1.ControlMapping.source_resource:type_name -> oscal.mapping.v1.MappingResourceReference
	2,  // 18: oscal.mapping.v1.ControlMapping.target_resource:type_name -> oscal.mapping.v1.MappingResourceReference
	3,  // 19: oscal.mapping.v1.ControlMapping.maps:type_name -> oscal.mapping.v1.Map
	15, // 20: oscal.mapping.v1.ControlMapping.props:type_name -> oscal.common.v1.Property
	16, // 21: oscal.mapping.v1.ControlMapping.links:type_name -> oscal.common.v1.Link
	17, // 22: oscal.mapping.v1.ControlMapping.remarks:type_name -> oscal.common.v1.MarkupMultiline
	17, // 23: oscal.mapping.v1.ControlMapping.mapping_description:type_name -> oscal.common.v1.MarkupMultiline
	8,  // 24: oscal.mapping.v1.ControlMapping.source_gap_summary:type_name -> oscal.mapping.v1.GapSummary
	8,  // 25: oscal.mapping.v1.ControlMapping.target_gap_summary:type_name -> oscal.mapping.v1.GapSummary
	6,  // 26: oscal.mapping.v1.ControlMapping.confidence_score:type_name -> oscal.mapping.v1.ConfidenceScore
	7,  // 27: oscal.mapping.v1.ControlMapping.coverage:type_name -> oscal.mapping.v1.Coverage
	19, // 28: oscal.mapping.v1.MappingResourceReference.href:type_name -> oscal.common.v1.URIReference
	15, // 29: oscal.mapping.v1.MappingResourceReference.props:type_name -> oscal.common.v1.Property
	16, // 30: oscal.mapping.v1.MappingResourceReference.links:type_name -> oscal.common.v1.Link
	17, // 31: oscal.mapping.v1.MappingResourceReference.remarks:type_name -> oscal.common.v1.MarkupMultiline
	13, // 32: oscal.mapping.v1.Map.uuid:type_name -> oscal.common.v1.UUID
	20, // 33: oscal.mapping.v1.Map.relationship:type_name -> oscal.common.v1.Token
	4,  // 34: oscal.mapping.v1.Map.sources:type_name -> oscal.mapping.v1.MappingItem
	4,  // 35: oscal.mapping.v1.Map.targets:type_name -> oscal.mapping.v1.MappingItem
	5,  // 36: oscal.mapping.v1.Map.qualifiers:type_name -> oscal.mapping.v1.QualifierItem
	6,  // 37: oscal.mapping.v1.Map.confidence_score:type_name -> oscal.mapping.v1.ConfidenceScore
	7,  // 38: oscal.mapping.v1.Map.coverage:type_name -> oscal.mapping.v1.Coverage
	15, // 39: oscal.mapping.v1.Map.props:type_name -> oscal.common.v1.Property
	16, // 40: oscal.mapping.v1.Map.links:type_name -> oscal.common.v1.Link
	17, // 41: oscal.mapping.v1.Map.remarks:type_name -> oscal.common.v1.MarkupMultiline
	15, // 42: oscal.mapping.v1.MappingItem.props:type_name -> oscal.common.v1.Property
	16, // 43: oscal.mapping.v1.MappingItem.links:type_name -> oscal.common.v1.Link
	17, // 44: oscal.mapping.v1.MappingItem.remarks:type_name -> oscal.common.v1.MarkupMultiline
	15, // 45: oscal.mapping.v1.QualifierItem.props:type_name -> oscal.common.v1.Property
	16, // 46: oscal.mapping.v1.QualifierItem.links:type_name -> oscal.common.v1.Link
	17, // 47: oscal.mapping.v1.QualifierItem.remarks:type_name -> oscal.common.v1.MarkupMultiline
	17, // 48: oscal.mapping.v1.QualifierItem.description:type_name -> oscal.common.v1.MarkupMultiline
	15, // 49: oscal.mapping.v1.ConfidenceScore.props:type_name -> oscal.common.v1.Property
	16, // 50: oscal.mapping.v1.ConfidenceScore.links:type_name -> oscal.common.v1.Link
	17, // 51: oscal.mapping.v1.ConfidenceScore.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21, // 52: oscal.mapping.v1.ConfidenceScore.percentage:type_name -> oscal.common.v1.Decimal
	15, // 53: oscal.mapping.v1.Coverage.props:type_name -> oscal.common.v1.Property
	16, // 54: oscal.mapping.v1.Coverage.links:type_name -> oscal.common.v1.Link
	17, // 55: oscal.mapping.v1.Coverage.remarks:type_name -> oscal.common.v1.MarkupMultiline
	21, // 56: oscal.mapping.v1.Coverage.target_coverage:type_name -> oscal.common.v1.Decimal
	15, // 57: oscal.mapping.v1.GapSummary.props:type_name -> oscal.common.v1.Property
	16, // 58: oscal.mapping.v1.GapSummary.links:type_name -> oscal.common.v1.Link
	17, // 59: oscal.mapping.v1.GapSummary.remarks:type_name -> oscal.common.v1.MarkupMultiline
	13, // 60: oscal.mapping.v1.GapSummary.uuid:type_name -> oscal.common.v1.UUID
	11, // 61: oscal.mapping.v1.GapSummary.unmapped_controls:type_name -> oscal.mapping.v1.SelectControlById
	17, // 62: oscal.mapping.v1.MappingDescription.description:type_name -> oscal.common.v1.MarkupMultiline
	15, // 63: oscal.mapping.v1.MappingDescription.props:type_name -> oscal.common.v1.Property
	16, // 64: oscal.mapping.v1.MappingDescription.links:type_name -> oscal.common.v1.Link
	17, // 65: oscal.mapping.v1.MappingDescription.remarks:type_name -> oscal.common.v1.MarkupMultiline
	6,  // 66: oscal.mapping.v1.MappingProvenance.confidence_score:type_name -> oscal.mapping.v1.ConfidenceScore
	7,  // 67: oscal.mapping.v1.MappingProvenance.coverage:type_name -> oscal.mapping.v1.Coverage
	17, // 68: oscal.mapping.v1.MappingProvenance.mapping_description:type_name -> oscal.common.v1.MarkupMultiline
	22, // 69: oscal.mapping.v1.MappingProvenance.responsible_parties:type_name -> oscal.common.v1.ResponsibleParty
	15, // 70: oscal.mapping.v1.MappingProvenance.props:type_name -> oscal.common.v1.Property
	16, // 71: oscal.mapping.v1.MappingProvenance.links:type_name -> oscal.common.v1.Link
	17, // 72: oscal.mapping.v1.MappingProvenance.remarks:type_name -> oscal.common.v1.MarkupMultiline
	20, // 73: oscal.mapping.v1.SelectControlById.with_ids:type_name -> oscal.common.v1.Token
	12, // 74: oscal.mapping.v1.SelectControlById.matching:type_name -> oscal.mapping.v1.Matching
	17, // 75: oscal.mapping.v1.Matching.remarks:type_name -> oscal.common.v1.MarkupMultiline
	76, // [76:76] is the sub-list for method output_type
	76, // [76:76] is the sub-list for method input_type
	76, // [76:76] is the sub-list for extension type_name
	76, // [76:76] is the sub-list for extension extendee
	0,  // [0:76] is the sub-list for field type_name
}

func init() { file_mapping_v1_mapping_proto_init() }
func file_mapping_v1_mapping_proto_init() {
	if File_mapping_v1_mapping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapping_v1_mapping_proto_rawDesc), len(file_mapping_v1_mapping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapping_v1_mapping_proto_goTypes,
		DependencyIndexes: file_mapping_v1_mapping_proto_depIdxs,
		MessageInfos:      file_mapping_v1_mapping_proto_msgTypes,
	}.Build()
	File_mapping_v1_mapping_proto = out.File
	file_mapping_v1_mapping_proto_goTypes = nil
	file_mapping_v1_mapping_proto_depIdxs = nil
}
